import { build } from "esbuild";
await build({
  entryPoints: ["src/index.ts"],
  bundle: true,
  format: "esm",
  platform: "browser",
  target: "es2022",
  outfile: "dist/worker.js",
});
await build({
  entryPoints: ["browser/crypto-worker.js"],
  bundle: true,
  format: "esm",
  platform: "browser",
  target: "es2022",
  minify: true,
  legalComments: "eof",
  outfile: "../lit-static/dapps/dashboard/password-crypto-worker.js",
  banner: {
    js: "// Generated by lit-dashboard-auth/scripts/build.mjs; hash-wasm 4.12.0 (MIT). Do not edit.",
  },
});
await build({
  entryPoints: ["browser/crypto-worker.js"],
  bundle: true,
  format: "esm",
  platform: "node",
  target: "es2022",
  outfile: "dist/crypto.js",
});
