import { build } from "esbuild";
// Browser bundle (committed; CI verifies it matches this source).
await build({
  entryPoints: ["browser/crypto-worker.js"],
  bundle: true,
  format: "esm",
  platform: "browser",
  target: "es2022",
  minify: true,
  legalComments: "eof",
  outfile: "../lit-static/dapps/dashboard/password-crypto-worker.js",
  banner: {
    js: "// Generated by lit-dashboard-auth/scripts/build.mjs; hash-wasm 4.12.0 (MIT). Do not edit.",
  },
});
// Node build of the same crypto for the API tests.
await build({
  entryPoints: ["browser/crypto-worker.js"],
  bundle: true,
  format: "esm",
  platform: "node",
  target: "es2022",
  outfile: "dist/crypto.js",
});
