[workspace]
members = ["cli", "ext", "grpc", "gvisor-server", "server", "snapshot", "tests"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
publish = false

[workspace.dependencies]
anyhow = "1"
flume = "0.11"
indoc = "2"
opentelemetry = "0.23"
opentelemetry-semantic-conventions = "0.15.0"
opentelemetry_sdk = "0.23.0"
serde_json = "1"
tokio = { version = "1", features = ["full"] }
tokio-stream = { version = "0.1", features = ["net"] }
tonic = "0.12.3"
tonic-build = "0.12.3"
tonic-reflection = "0.12.3"
tracing = "0.1"
tracing-appender = { version = "0.2" }
tracing-opentelemetry = { version = "0.25" }
tracing-subscriber = { version = "0.3" }

# Deno v2.8.0
deno_core = "=0.401.0"
deno_error = "=0.7.1"
deno_lib = "=0.66.0"
deno_resolver = "=0.79.0"
deno_runtime = "=0.256.0"
sys_traits = "=0.1.28"

lit-actions-ext = { path = "ext" }
lit-actions-grpc = { path = "grpc" }
lit-actions-server = { path = "server" }
lit-actions-snapshot = { path = "snapshot" }
lit-api-core = { path = "../lit-core/lit-api-core" }
lit-core = { path = "../lit-core/lit-core", features = ["unix"] }
lit-observability = { path = "../lit-core/lit-observability" }

[workspace.metadata.cargo-machete]
ignored = ["prost"]

# Please keep all profiles in sync with lit-node
[profile.release]
codegen-units = 1
incremental = true
lto = true
opt-level = 3

[profile.develop]
inherits = "dev"
opt-level = 1
debug = 1
incremental = false

# rusty-v8 needs at least -O1 to not miscompile
[profile.dev.package.v8]
opt-level = 1
