/**
 * Automatically generated by @grafana/openapi-to-k6: 0.4.1
 * Do not edit manually.
 * lit-api-server
 * Lit Express Node API Server
 * Service version: 0.1.0
 */
import { URL, URLSearchParams } from "https://jslib.k6.io/url/1.0.0/index.js";

import http from "k6/http";
import type { Params, Response } from "k6/http";

/**
 * One item from list_api_keys (AccountConfig.sol UsageApiKey).
 */
export interface ApiKeyItem {
  id: string;
  api_key_hash: string;
  name: string;
  description: string;
  expiration: string;
  /** @minimum 0 */
  balance: number;
  can_create_groups: boolean;
  can_delete_groups: boolean;
  can_create_pkps: boolean;
  can_manage_ipfs_ids_in_groups: number[];
  can_add_pkp_to_groups: number[];
  can_remove_pkp_from_groups: number[];
  can_execute_in_groups: number[];
}

export type ErrMessage = string;

export interface NewAccountResponse {
  api_key: string;
  wallet_address: string;
}

export interface NewAccountRequest {
  account_name: string;
  account_description: string;
  /**
   * Optional email address — forwarded to Stripe for the customer record.  Not stored on-chain.
   * @nullable
   */
  email?: string | null;
}

export interface CreateWalletResponse {
  wallet_address: string;
}

export interface LitActionResponse {
  response: unknown;
  logs: string;
  has_error: boolean;
}

/**
 * @nullable
 */
export type LitActionRequestJsParams = unknown | null;

/**
 * API key via header.
 */
export interface LitActionRequest {
  code: string;
  /** @nullable */
  js_params?: LitActionRequestJsParams;
}

/**
 * Response for account config operations (add_pkp_to_group, remove_pkp_from_group, add_usage_api_key, remove_usage_api_key).
 */
export interface AccountOpResponse {
  success: boolean;
}

/**
 * Response for add_group, includes the on-chain group ID.
 */
export interface AddGroupResponse {
  success: boolean;
  group_id: string;
}

/**
 * Request for add_group. permitted_actions and pkps are keccak256 hashes as hex strings (with or without 0x). API key via header.
 */
export interface AddGroupRequest {
  /** Name of the group (Group.metadata.name in AccountConfig.sol). */
  group_name: string;
  /** Description of the group (Group.metadata.description in AccountConfig.sol). */
  group_description: string;
  /** pkp ids permitted to use the group (AccountConfig.sol Group.pkpId). */
  pkp_ids_permitted: string[];
  /** Actions permitted to use the group (AccountConfig.sol Group.cidHash). */
  cid_hashes_permitted: string[];
}

export interface RemoveGroupRequest {
  group_id: string;
}

export interface AddActionRequest {
  /** IPFS CID for the action (keccak256-hashed on server). */
  action_ipfs_cid: string;
  name: string;
  description: string;
}

/**
 * Request for delete_action. hashed_cid is already a keccak256 hash (hex string). API key via header.
 */
export interface DeleteActionRequest {
  /** Already-hashed CID for the action (0x-prefixed hex string). */
  hashed_cid: string;
}

export interface AddActionToGroupRequest {
  /** @minimum 0 */
  group_id: number;
  /** IPFS CID for the action (will be keccak256-hashed on server). */
  action_ipfs_cid: string;
}

export interface AddPkpToGroupRequest {
  /**
   * Group ID (decimal or hex string).
   * @minimum 0
   */
  group_id: number;
  pkp_id: string;
}

export interface RemovePkpFromGroupRequest {
  /** @minimum 0 */
  group_id: number;
  pkp_id: string;
}

/**
 * Response for account config operations (add_group, add_pkp_to_group, remove_pkp_from_group, add_usage_api_key, remove_usage_api_key).
 */
export interface AddUsageApiKeyResponse {
  success: boolean;
  usage_api_key: string;
}

/**
 * Request for add_usage_api_key. expiration and balance as decimal strings (e.g. unix timestamp, wei). API key via header.
 */
export interface AddUsageApiKeyRequest {
  name: string;
  description: string;
  can_create_groups: boolean;
  can_delete_groups: boolean;
  can_create_pkps: boolean;
  /** Group IDs to grant manage-IPFS-IDs permission. 0 is wildcard for all groups. */
  manage_ipfs_ids_in_groups: number[];
  /** Group IDs to grant add-PKP permission. 0 is wildcard for all groups. */
  add_pkp_to_groups: number[];
  /** Group IDs to grant remove-PKP permission. 0 is wildcard for all groups. */
  remove_pkp_from_groups: number[];
  /** Group IDs to grant execute permission. 0 is wildcard for all groups. */
  execute_in_groups: number[];
}

/**
 * Request for update_usage_api_key. Updates all permissions and metadata on an existing usage API key. API key via header.
 */
export interface UpdateUsageApiKeyRequest {
  usage_api_key: string;
  name: string;
  description: string;
  can_create_groups: boolean;
  can_delete_groups: boolean;
  can_create_pkps: boolean;
  /** Group IDs to grant manage-IPFS-IDs permission. 0 is wildcard for all groups. */
  manage_ipfs_ids_in_groups: number[];
  /** Group IDs to grant add-PKP permission. 0 is wildcard for all groups. */
  add_pkp_to_groups: number[];
  /** Group IDs to grant remove-PKP permission. 0 is wildcard for all groups. */
  remove_pkp_from_groups: number[];
  /** Group IDs to grant execute permission. 0 is wildcard for all groups. */
  execute_in_groups: number[];
}

/**
 * API key via header.
 */
export interface RemoveUsageApiKeyRequest {
  usage_api_key: string;
}

/**
 * Request for update_group (AccountConfig.updateGroup). API key via header.
 */
export interface UpdateGroupRequest {
  /**
   * Group ID (decimal or hex string).
   * @minimum 0
   */
  group_id: number;
  name: string;
  description: string;
  pkp_ids_permitted?: string[];
  cid_hashes_permitted?: string[];
}

/**
 * Request for remove_action_from_group. hashed_cid is already a keccak256 hash (hex string). API key via header.
 */
export interface RemoveActionFromGroupRequest {
  /** @minimum 0 */
  group_id: number;
  /** Already-hashed CID for the action (0x-prefixed hex string). */
  hashed_cid: string;
}

/**
 * Request for update_action_metadata. hashed_cid is already a keccak256 hash (hex string). API key via header.
 */
export interface UpdateActionMetadataRequest {
  /** Already-hashed CID for the action (0x-prefixed hex string). */
  hashed_cid: string;
  name: string;
  description: string;
}

/**
 * Request for update_usage_api_key_metadata (AccountConfig.updateUsageApiKeyMetadata). API key via header.
 */
export interface UpdateUsageApiKeyMetadataRequest {
  usage_api_key: string;
  name: string;
  description: string;
}

/**
 * One item from list_groups, list_wallets, list_wallets_in_group, or list_actions (AccountConfig.sol Metadata).
 */
export interface ListMetadataItem {
  id: string;
  name: string;
  description: string;
}

/**
 * One item from list_groups, list_wallets, list_wallets_in_group, or list_actions (AccountConfig.sol Metadata).
 */
export interface WalletItem {
  id: string;
  name: string;
  description: string;
  wallet_address: string;
}

export interface NodeChainConfigResponse {
  chain_name: string;
  /** @minimum 0 */
  chain_id: number;
  is_evm: boolean;
  testnet: boolean;
  token: string;
  contract_address: string;
}

/**
 * GET /get_chain_config_keys — names of every supported ConfigKeys variant.
 */
export interface ChainConfigKeysResponse {
  keys: string[];
}

/**
 * GET /get_lit_action_client_config — effective ClientBuilder configuration values, including any chain-config overrides applied at startup.
 */
export interface LitActionClientConfigResponse {
  /** @minimum 0 */
  timeout_ms: number;
  /** @minimum 0 */
  async_timeout_ms: number;
  /** @minimum 0 */
  memory_limit_mb: number;
  /** @minimum 0 */
  max_code_length: number;
  /** @minimum 0 */
  max_response_length: number;
  /** @minimum 0 */
  max_console_log_length: number;
  /** @minimum 0 */
  max_fetch_count: number;
  /** @minimum 0 */
  max_get_keys_count: number;
  /** @minimum 0 */
  max_retries: number;
  /** @minimum 0 */
  client_timeout_ms_buffer: number;
}

/**
 * GET /billing/stripe_config — returns the Stripe publishable key for Stripe.js.
 */
export interface StripeConfigResponse {
  publishable_key: string;
}

/**
 * GET /billing/balance — current credit balance for the authenticated API key.
 */
export interface BillingBalanceResponse {
  /** Balance in cents.  Negative means credits are available; zero means exhausted. */
  balance_cents: number;
  /** Human-readable, e.g. "$5.00 credit". */
  balance_display: string;
}

/**
 * POST /billing/create_payment_intent — client secret for Stripe.js confirmCardPayment.
 */
export interface CreatePaymentIntentResponse {
  client_secret: string;
  payment_intent_id: string;
}

/**
 * POST /billing/create_payment_intent
 */
export interface CreatePaymentIntentRequest {
  /** Amount to charge in US cents (minimum 500 = $5.00). */
  amount_cents: number;
}

/**
 * POST /billing/confirm_payment
 */
export interface ConfirmPaymentRequest {
  payment_intent_id: string;
}

export interface VersionResponse {
  name: string;
  version: string;
  commit_version: string;
  submodule_versions: unknown[][];
}

export type ListApiKeysParams = {
  /**
   * @minimum 0
   */
  page_number: number;
  /**
   * @minimum 0
   */
  page_size: number;
};

export type ListApiKeysHeaders = {
  /**
   * Account or usage API key. Alternatively use Authorization: Bearer <key>.
   */
  "X-Api-Key": string;
};

export type ListApiKeysDefault = ApiKeyItem[] | ErrMessage;

export type NewAccountDefault = NewAccountResponse | ErrMessage;

export type AccountExistsHeaders = {
  /**
   * Account or usage API key. Alternatively use Authorization: Bearer <key>.
   */
  "X-Api-Key": string;
};

export type AccountExistsDefault = boolean | ErrMessage;

export type CreateWalletHeaders = {
  /**
   * Account or usage API key. Alternatively use Authorization: Bearer <key>.
   */
  "X-Api-Key": string;
};

export type CreateWalletDefault = CreateWalletResponse | ErrMessage;

export type LitActionHeaders = {
  /**
   * Account or usage API key. Alternatively use Authorization: Bearer <key>.
   */
  "X-Api-Key": string;
};

export type LitActionDefault = LitActionResponse | ErrMessage;

export type GetLitActionIpfsIdDefault = string | ErrMessage;

export type AddGroupHeaders = {
  /**
   * Account or usage API key. Alternatively use Authorization: Bearer <key>.
   */
  "X-Api-Key": string;
};

export type AddGroupDefault = AddGroupResponse | ErrMessage;

export type RemoveGroupHeaders = {
  /**
   * Account or usage API key. Alternatively use Authorization: Bearer <key>.
   */
  "X-Api-Key": string;
};

export type RemoveGroupDefault = AccountOpResponse | ErrMessage;

export type AddActionHeaders = {
  /**
   * Account or usage API key. Alternatively use Authorization: Bearer <key>.
   */
  "X-Api-Key": string;
};

export type AddActionDefault = AccountOpResponse | ErrMessage;

export type DeleteActionHeaders = {
  /**
   * Account or usage API key. Alternatively use Authorization: Bearer <key>.
   */
  "X-Api-Key": string;
};

export type DeleteActionDefault = AccountOpResponse | ErrMessage;

export type AddActionToGroupHeaders = {
  /**
   * Account or usage API key. Alternatively use Authorization: Bearer <key>.
   */
  "X-Api-Key": string;
};

export type AddActionToGroupDefault = AccountOpResponse | ErrMessage;

export type AddPkpToGroupHeaders = {
  /**
   * Account or usage API key. Alternatively use Authorization: Bearer <key>.
   */
  "X-Api-Key": string;
};

export type AddPkpToGroupDefault = AccountOpResponse | ErrMessage;

export type RemovePkpFromGroupHeaders = {
  /**
   * Account or usage API key. Alternatively use Authorization: Bearer <key>.
   */
  "X-Api-Key": string;
};

export type RemovePkpFromGroupDefault = AccountOpResponse | ErrMessage;

export type AddUsageApiKeyHeaders = {
  /**
   * Account or usage API key. Alternatively use Authorization: Bearer <key>.
   */
  "X-Api-Key": string;
};

export type AddUsageApiKeyDefault = AddUsageApiKeyResponse | ErrMessage;

export type UpdateUsageApiKeyHeaders = {
  /**
   * Account or usage API key. Alternatively use Authorization: Bearer <key>.
   */
  "X-Api-Key": string;
};

export type UpdateUsageApiKeyDefault = AccountOpResponse | ErrMessage;

export type RemoveUsageApiKeyHeaders = {
  /**
   * Account or usage API key. Alternatively use Authorization: Bearer <key>.
   */
  "X-Api-Key": string;
};

export type RemoveUsageApiKeyDefault = AccountOpResponse | ErrMessage;

export type UpdateGroupHeaders = {
  /**
   * Account or usage API key. Alternatively use Authorization: Bearer <key>.
   */
  "X-Api-Key": string;
};

export type UpdateGroupDefault = AccountOpResponse | ErrMessage;

export type RemoveActionFromGroupHeaders = {
  /**
   * Account or usage API key. Alternatively use Authorization: Bearer <key>.
   */
  "X-Api-Key": string;
};

export type RemoveActionFromGroupDefault = AccountOpResponse | ErrMessage;

export type UpdateActionMetadataHeaders = {
  /**
   * Account or usage API key. Alternatively use Authorization: Bearer <key>.
   */
  "X-Api-Key": string;
};

export type UpdateActionMetadataDefault = AccountOpResponse | ErrMessage;

export type UpdateUsageApiKeyMetadataHeaders = {
  /**
   * Account or usage API key. Alternatively use Authorization: Bearer <key>.
   */
  "X-Api-Key": string;
};

export type UpdateUsageApiKeyMetadataDefault = AccountOpResponse | ErrMessage;

export type ListGroupsParams = {
  /**
   * @minimum 0
   */
  page_number: number;
  /**
   * @minimum 0
   */
  page_size: number;
};

export type ListGroupsHeaders = {
  /**
   * Account or usage API key. Alternatively use Authorization: Bearer <key>.
   */
  "X-Api-Key": string;
};

export type ListGroupsDefault = ListMetadataItem[] | ErrMessage;

export type ListWalletsParams = {
  /**
   * @minimum 0
   */
  page_number: number;
  /**
   * @minimum 0
   */
  page_size: number;
};

export type ListWalletsHeaders = {
  /**
   * Account or usage API key. Alternatively use Authorization: Bearer <key>.
   */
  "X-Api-Key": string;
};

export type ListWalletsDefault = WalletItem[] | ErrMessage;

export type ListWalletsInGroupParams = {
  /**
   * @minimum 0
   */
  group_id: number;
  /**
   * @minimum 0
   */
  page_number: number;
  /**
   * @minimum 0
   */
  page_size: number;
};

export type ListWalletsInGroupHeaders = {
  /**
   * Account or usage API key. Alternatively use Authorization: Bearer <key>.
   */
  "X-Api-Key": string;
};

export type ListWalletsInGroupDefault = WalletItem[] | ErrMessage;

export type ListActionsParams = {
  /**
   * @nullable
   */
  group_id?: string | null;
  /**
   * @minimum 0
   */
  page_number: number;
  /**
   * @minimum 0
   */
  page_size: number;
};

export type ListActionsHeaders = {
  /**
   * Account or usage API key. Alternatively use Authorization: Bearer <key>.
   */
  "X-Api-Key": string;
};

export type ListActionsDefault = ListMetadataItem[] | ErrMessage;

export type GetNodeChainConfigDefault = NodeChainConfigResponse | ErrMessage;

export type GetChainConfigKeysDefault = ChainConfigKeysResponse | ErrMessage;

export type GetLitActionClientConfigDefault =
  | LitActionClientConfigResponse
  | ErrMessage;

export type GetApiPayersDefault = string[] | ErrMessage;

export type GetAdminApiPayerDefault = string | ErrMessage;

export type BillingStripeConfigDefault = StripeConfigResponse | ErrMessage;

export type BillingBalanceHeaders = {
  /**
   * Account or usage API key. Alternatively use Authorization: Bearer <key>.
   */
  "X-Api-Key": string;
};

export type BillingBalanceDefault = BillingBalanceResponse | ErrMessage;

export type BillingCreatePaymentIntentHeaders = {
  /**
   * Account or usage API key. Alternatively use Authorization: Bearer <key>.
   */
  "X-Api-Key": string;
};

export type BillingCreatePaymentIntentDefault =
  | CreatePaymentIntentResponse
  | ErrMessage;

export type BillingConfirmPaymentHeaders = {
  /**
   * Account or usage API key. Alternatively use Authorization: Bearer <key>.
   */
  "X-Api-Key": string;
};

export type BillingConfirmPaymentDefault = AccountOpResponse | ErrMessage;

export type GetVersionDefault = VersionResponse | ErrMessage;

/**
 * This is the base client to use for interacting with the API.
 */
export class LitApiServerClient {
  private cleanBaseUrl: string;
  private commonRequestParameters: Params;

  constructor(clientOptions: {
    baseUrl: string;
    commonRequestParameters?: Params;
  }) {
    this.cleanBaseUrl = clientOptions.baseUrl.replace(/\/+$/, "");

    this.commonRequestParameters = clientOptions.commonRequestParameters || {};
  }

  listApiKeys(
    params: ListApiKeysParams,
    headers: ListApiKeysHeaders,
    requestParameters?: Params,
  ): {
    response: Response;
    data: ListApiKeysDefault;
    operationId: string;
  } {
    const k6url = new URL(
      this.cleanBaseUrl +
        `/list_api_keys` +
        `?${new URLSearchParams(params).toString()}`,
    );
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request("GET", k6url.toString(), undefined, {
      ...mergedRequestParameters,
      headers: {
        ...mergedRequestParameters?.headers,
        // In the schema, headers can be of any type like number but k6 accepts only strings as headers, hence converting all headers to string
        ...Object.fromEntries(
          Object.entries(headers || {}).map(([key, value]) => [
            key,
            String(value),
          ]),
        ),
      },
    });
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
      operationId: "list_api_keys",
    };
  }

  newAccount(
    newAccountRequest: NewAccountRequest,
    requestParameters?: Params,
  ): {
    response: Response;
    data: NewAccountDefault;
    operationId: string;
  } {
    const k6url = new URL(this.cleanBaseUrl + `/new_account`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "POST",
      k6url.toString(),
      JSON.stringify(newAccountRequest),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          "Content-Type": "application/json",
        },
      },
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
      operationId: "new_account",
    };
  }

  accountExists(
    headers: AccountExistsHeaders,
    requestParameters?: Params,
  ): {
    response: Response;
    data: AccountExistsDefault;
    operationId: string;
  } {
    const k6url = new URL(this.cleanBaseUrl + `/account_exists`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request("GET", k6url.toString(), undefined, {
      ...mergedRequestParameters,
      headers: {
        ...mergedRequestParameters?.headers,
        // In the schema, headers can be of any type like number but k6 accepts only strings as headers, hence converting all headers to string
        ...Object.fromEntries(
          Object.entries(headers || {}).map(([key, value]) => [
            key,
            String(value),
          ]),
        ),
      },
    });
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
      operationId: "account_exists",
    };
  }

  createWallet(
    headers: CreateWalletHeaders,
    requestParameters?: Params,
  ): {
    response: Response;
    data: CreateWalletDefault;
    operationId: string;
  } {
    const k6url = new URL(this.cleanBaseUrl + `/create_wallet`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request("GET", k6url.toString(), undefined, {
      ...mergedRequestParameters,
      headers: {
        ...mergedRequestParameters?.headers,
        // In the schema, headers can be of any type like number but k6 accepts only strings as headers, hence converting all headers to string
        ...Object.fromEntries(
          Object.entries(headers || {}).map(([key, value]) => [
            key,
            String(value),
          ]),
        ),
      },
    });
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
      operationId: "create_wallet",
    };
  }

  litAction(
    litActionRequest: LitActionRequest,
    headers: LitActionHeaders,
    requestParameters?: Params,
  ): {
    response: Response;
    data: LitActionDefault;
    operationId: string;
  } {
    const k6url = new URL(this.cleanBaseUrl + `/lit_action`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "POST",
      k6url.toString(),
      JSON.stringify(litActionRequest),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          "Content-Type": "application/json",
          // In the schema, headers can be of any type like number but k6 accepts only strings as headers, hence converting all headers to string
          ...Object.fromEntries(
            Object.entries(headers || {}).map(([key, value]) => [
              key,
              String(value),
            ]),
          ),
        },
      },
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
      operationId: "lit_action",
    };
  }

  getLitActionIpfsId(
    getLitActionIpfsIdBody: string,
    requestParameters?: Params,
  ): {
    response: Response;
    data: GetLitActionIpfsIdDefault;
    operationId: string;
  } {
    const k6url = new URL(this.cleanBaseUrl + `/get_lit_action_ipfs_id`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "POST",
      k6url.toString(),
      JSON.stringify(getLitActionIpfsIdBody),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          "Content-Type": "application/json",
        },
      },
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
      operationId: "get_lit_action_ipfs_id",
    };
  }

  addGroup(
    addGroupRequest: AddGroupRequest,
    headers: AddGroupHeaders,
    requestParameters?: Params,
  ): {
    response: Response;
    data: AddGroupDefault;
    operationId: string;
  } {
    const k6url = new URL(this.cleanBaseUrl + `/add_group`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "POST",
      k6url.toString(),
      JSON.stringify(addGroupRequest),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          "Content-Type": "application/json",
          // In the schema, headers can be of any type like number but k6 accepts only strings as headers, hence converting all headers to string
          ...Object.fromEntries(
            Object.entries(headers || {}).map(([key, value]) => [
              key,
              String(value),
            ]),
          ),
        },
      },
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
      operationId: "add_group",
    };
  }

  removeGroup(
    removeGroupRequest: RemoveGroupRequest,
    headers: RemoveGroupHeaders,
    requestParameters?: Params,
  ): {
    response: Response;
    data: RemoveGroupDefault;
    operationId: string;
  } {
    const k6url = new URL(this.cleanBaseUrl + `/remove_group`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "POST",
      k6url.toString(),
      JSON.stringify(removeGroupRequest),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          "Content-Type": "application/json",
          // In the schema, headers can be of any type like number but k6 accepts only strings as headers, hence converting all headers to string
          ...Object.fromEntries(
            Object.entries(headers || {}).map(([key, value]) => [
              key,
              String(value),
            ]),
          ),
        },
      },
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
      operationId: "remove_group",
    };
  }

  addAction(
    addActionRequest: AddActionRequest,
    headers: AddActionHeaders,
    requestParameters?: Params,
  ): {
    response: Response;
    data: AddActionDefault;
    operationId: string;
  } {
    const k6url = new URL(this.cleanBaseUrl + `/add_action`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "POST",
      k6url.toString(),
      JSON.stringify(addActionRequest),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          "Content-Type": "application/json",
          // In the schema, headers can be of any type like number but k6 accepts only strings as headers, hence converting all headers to string
          ...Object.fromEntries(
            Object.entries(headers || {}).map(([key, value]) => [
              key,
              String(value),
            ]),
          ),
        },
      },
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
      operationId: "add_action",
    };
  }

  deleteAction(
    deleteActionRequest: DeleteActionRequest,
    headers: DeleteActionHeaders,
    requestParameters?: Params,
  ): {
    response: Response;
    data: DeleteActionDefault;
    operationId: string;
  } {
    const k6url = new URL(this.cleanBaseUrl + `/delete_action`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "POST",
      k6url.toString(),
      JSON.stringify(deleteActionRequest),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          "Content-Type": "application/json",
          // In the schema, headers can be of any type like number but k6 accepts only strings as headers, hence converting all headers to string
          ...Object.fromEntries(
            Object.entries(headers || {}).map(([key, value]) => [
              key,
              String(value),
            ]),
          ),
        },
      },
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
      operationId: "delete_action",
    };
  }

  addActionToGroup(
    addActionToGroupRequest: AddActionToGroupRequest,
    headers: AddActionToGroupHeaders,
    requestParameters?: Params,
  ): {
    response: Response;
    data: AddActionToGroupDefault;
    operationId: string;
  } {
    const k6url = new URL(this.cleanBaseUrl + `/add_action_to_group`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "POST",
      k6url.toString(),
      JSON.stringify(addActionToGroupRequest),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          "Content-Type": "application/json",
          // In the schema, headers can be of any type like number but k6 accepts only strings as headers, hence converting all headers to string
          ...Object.fromEntries(
            Object.entries(headers || {}).map(([key, value]) => [
              key,
              String(value),
            ]),
          ),
        },
      },
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
      operationId: "add_action_to_group",
    };
  }

  addPkpToGroup(
    addPkpToGroupRequest: AddPkpToGroupRequest,
    headers: AddPkpToGroupHeaders,
    requestParameters?: Params,
  ): {
    response: Response;
    data: AddPkpToGroupDefault;
    operationId: string;
  } {
    const k6url = new URL(this.cleanBaseUrl + `/add_pkp_to_group`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "POST",
      k6url.toString(),
      JSON.stringify(addPkpToGroupRequest),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          "Content-Type": "application/json",
          // In the schema, headers can be of any type like number but k6 accepts only strings as headers, hence converting all headers to string
          ...Object.fromEntries(
            Object.entries(headers || {}).map(([key, value]) => [
              key,
              String(value),
            ]),
          ),
        },
      },
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
      operationId: "add_pkp_to_group",
    };
  }

  removePkpFromGroup(
    removePkpFromGroupRequest: RemovePkpFromGroupRequest,
    headers: RemovePkpFromGroupHeaders,
    requestParameters?: Params,
  ): {
    response: Response;
    data: RemovePkpFromGroupDefault;
    operationId: string;
  } {
    const k6url = new URL(this.cleanBaseUrl + `/remove_pkp_from_group`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "POST",
      k6url.toString(),
      JSON.stringify(removePkpFromGroupRequest),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          "Content-Type": "application/json",
          // In the schema, headers can be of any type like number but k6 accepts only strings as headers, hence converting all headers to string
          ...Object.fromEntries(
            Object.entries(headers || {}).map(([key, value]) => [
              key,
              String(value),
            ]),
          ),
        },
      },
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
      operationId: "remove_pkp_from_group",
    };
  }

  addUsageApiKey(
    addUsageApiKeyRequest: AddUsageApiKeyRequest,
    headers: AddUsageApiKeyHeaders,
    requestParameters?: Params,
  ): {
    response: Response;
    data: AddUsageApiKeyDefault;
    operationId: string;
  } {
    const k6url = new URL(this.cleanBaseUrl + `/add_usage_api_key`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "POST",
      k6url.toString(),
      JSON.stringify(addUsageApiKeyRequest),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          "Content-Type": "application/json",
          // In the schema, headers can be of any type like number but k6 accepts only strings as headers, hence converting all headers to string
          ...Object.fromEntries(
            Object.entries(headers || {}).map(([key, value]) => [
              key,
              String(value),
            ]),
          ),
        },
      },
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
      operationId: "add_usage_api_key",
    };
  }

  updateUsageApiKey(
    updateUsageApiKeyRequest: UpdateUsageApiKeyRequest,
    headers: UpdateUsageApiKeyHeaders,
    requestParameters?: Params,
  ): {
    response: Response;
    data: UpdateUsageApiKeyDefault;
    operationId: string;
  } {
    const k6url = new URL(this.cleanBaseUrl + `/update_usage_api_key`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "POST",
      k6url.toString(),
      JSON.stringify(updateUsageApiKeyRequest),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          "Content-Type": "application/json",
          // In the schema, headers can be of any type like number but k6 accepts only strings as headers, hence converting all headers to string
          ...Object.fromEntries(
            Object.entries(headers || {}).map(([key, value]) => [
              key,
              String(value),
            ]),
          ),
        },
      },
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
      operationId: "update_usage_api_key",
    };
  }

  removeUsageApiKey(
    removeUsageApiKeyRequest: RemoveUsageApiKeyRequest,
    headers: RemoveUsageApiKeyHeaders,
    requestParameters?: Params,
  ): {
    response: Response;
    data: RemoveUsageApiKeyDefault;
    operationId: string;
  } {
    const k6url = new URL(this.cleanBaseUrl + `/remove_usage_api_key`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "POST",
      k6url.toString(),
      JSON.stringify(removeUsageApiKeyRequest),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          "Content-Type": "application/json",
          // In the schema, headers can be of any type like number but k6 accepts only strings as headers, hence converting all headers to string
          ...Object.fromEntries(
            Object.entries(headers || {}).map(([key, value]) => [
              key,
              String(value),
            ]),
          ),
        },
      },
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
      operationId: "remove_usage_api_key",
    };
  }

  updateGroup(
    updateGroupRequest: UpdateGroupRequest,
    headers: UpdateGroupHeaders,
    requestParameters?: Params,
  ): {
    response: Response;
    data: UpdateGroupDefault;
    operationId: string;
  } {
    const k6url = new URL(this.cleanBaseUrl + `/update_group`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "POST",
      k6url.toString(),
      JSON.stringify(updateGroupRequest),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          "Content-Type": "application/json",
          // In the schema, headers can be of any type like number but k6 accepts only strings as headers, hence converting all headers to string
          ...Object.fromEntries(
            Object.entries(headers || {}).map(([key, value]) => [
              key,
              String(value),
            ]),
          ),
        },
      },
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
      operationId: "update_group",
    };
  }

  removeActionFromGroup(
    removeActionFromGroupRequest: RemoveActionFromGroupRequest,
    headers: RemoveActionFromGroupHeaders,
    requestParameters?: Params,
  ): {
    response: Response;
    data: RemoveActionFromGroupDefault;
    operationId: string;
  } {
    const k6url = new URL(this.cleanBaseUrl + `/remove_action_from_group`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "POST",
      k6url.toString(),
      JSON.stringify(removeActionFromGroupRequest),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          "Content-Type": "application/json",
          // In the schema, headers can be of any type like number but k6 accepts only strings as headers, hence converting all headers to string
          ...Object.fromEntries(
            Object.entries(headers || {}).map(([key, value]) => [
              key,
              String(value),
            ]),
          ),
        },
      },
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
      operationId: "remove_action_from_group",
    };
  }

  updateActionMetadata(
    updateActionMetadataRequest: UpdateActionMetadataRequest,
    headers: UpdateActionMetadataHeaders,
    requestParameters?: Params,
  ): {
    response: Response;
    data: UpdateActionMetadataDefault;
    operationId: string;
  } {
    const k6url = new URL(this.cleanBaseUrl + `/update_action_metadata`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "POST",
      k6url.toString(),
      JSON.stringify(updateActionMetadataRequest),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          "Content-Type": "application/json",
          // In the schema, headers can be of any type like number but k6 accepts only strings as headers, hence converting all headers to string
          ...Object.fromEntries(
            Object.entries(headers || {}).map(([key, value]) => [
              key,
              String(value),
            ]),
          ),
        },
      },
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
      operationId: "update_action_metadata",
    };
  }

  updateUsageApiKeyMetadata(
    updateUsageApiKeyMetadataRequest: UpdateUsageApiKeyMetadataRequest,
    headers: UpdateUsageApiKeyMetadataHeaders,
    requestParameters?: Params,
  ): {
    response: Response;
    data: UpdateUsageApiKeyMetadataDefault;
    operationId: string;
  } {
    const k6url = new URL(this.cleanBaseUrl + `/update_usage_api_key_metadata`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "POST",
      k6url.toString(),
      JSON.stringify(updateUsageApiKeyMetadataRequest),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          "Content-Type": "application/json",
          // In the schema, headers can be of any type like number but k6 accepts only strings as headers, hence converting all headers to string
          ...Object.fromEntries(
            Object.entries(headers || {}).map(([key, value]) => [
              key,
              String(value),
            ]),
          ),
        },
      },
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
      operationId: "update_usage_api_key_metadata",
    };
  }

  listGroups(
    params: ListGroupsParams,
    headers: ListGroupsHeaders,
    requestParameters?: Params,
  ): {
    response: Response;
    data: ListGroupsDefault;
    operationId: string;
  } {
    const k6url = new URL(
      this.cleanBaseUrl +
        `/list_groups` +
        `?${new URLSearchParams(params).toString()}`,
    );
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request("GET", k6url.toString(), undefined, {
      ...mergedRequestParameters,
      headers: {
        ...mergedRequestParameters?.headers,
        // In the schema, headers can be of any type like number but k6 accepts only strings as headers, hence converting all headers to string
        ...Object.fromEntries(
          Object.entries(headers || {}).map(([key, value]) => [
            key,
            String(value),
          ]),
        ),
      },
    });
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
      operationId: "list_groups",
    };
  }

  listWallets(
    params: ListWalletsParams,
    headers: ListWalletsHeaders,
    requestParameters?: Params,
  ): {
    response: Response;
    data: ListWalletsDefault;
    operationId: string;
  } {
    const k6url = new URL(
      this.cleanBaseUrl +
        `/list_wallets` +
        `?${new URLSearchParams(params).toString()}`,
    );
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request("GET", k6url.toString(), undefined, {
      ...mergedRequestParameters,
      headers: {
        ...mergedRequestParameters?.headers,
        // In the schema, headers can be of any type like number but k6 accepts only strings as headers, hence converting all headers to string
        ...Object.fromEntries(
          Object.entries(headers || {}).map(([key, value]) => [
            key,
            String(value),
          ]),
        ),
      },
    });
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
      operationId: "list_wallets",
    };
  }

  listWalletsInGroup(
    params: ListWalletsInGroupParams,
    headers: ListWalletsInGroupHeaders,
    requestParameters?: Params,
  ): {
    response: Response;
    data: ListWalletsInGroupDefault;
    operationId: string;
  } {
    const k6url = new URL(
      this.cleanBaseUrl +
        `/list_wallets_in_group` +
        `?${new URLSearchParams(params).toString()}`,
    );
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request("GET", k6url.toString(), undefined, {
      ...mergedRequestParameters,
      headers: {
        ...mergedRequestParameters?.headers,
        // In the schema, headers can be of any type like number but k6 accepts only strings as headers, hence converting all headers to string
        ...Object.fromEntries(
          Object.entries(headers || {}).map(([key, value]) => [
            key,
            String(value),
          ]),
        ),
      },
    });
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
      operationId: "list_wallets_in_group",
    };
  }

  listActions(
    params: ListActionsParams,
    headers: ListActionsHeaders,
    requestParameters?: Params,
  ): {
    response: Response;
    data: ListActionsDefault;
    operationId: string;
  } {
    const k6url = new URL(
      this.cleanBaseUrl +
        `/list_actions` +
        `?${new URLSearchParams(params).toString()}`,
    );
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request("GET", k6url.toString(), undefined, {
      ...mergedRequestParameters,
      headers: {
        ...mergedRequestParameters?.headers,
        // In the schema, headers can be of any type like number but k6 accepts only strings as headers, hence converting all headers to string
        ...Object.fromEntries(
          Object.entries(headers || {}).map(([key, value]) => [
            key,
            String(value),
          ]),
        ),
      },
    });
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
      operationId: "list_actions",
    };
  }

  getNodeChainConfig(requestParameters?: Params): {
    response: Response;
    data: GetNodeChainConfigDefault;
    operationId: string;
  } {
    const k6url = new URL(this.cleanBaseUrl + `/get_node_chain_config`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "GET",
      k6url.toString(),
      undefined,
      mergedRequestParameters,
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
      operationId: "get_node_chain_config",
    };
  }

  getChainConfigKeys(requestParameters?: Params): {
    response: Response;
    data: GetChainConfigKeysDefault;
    operationId: string;
  } {
    const k6url = new URL(this.cleanBaseUrl + `/get_chain_config_keys`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "GET",
      k6url.toString(),
      undefined,
      mergedRequestParameters,
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
      operationId: "get_chain_config_keys",
    };
  }

  getLitActionClientConfig(requestParameters?: Params): {
    response: Response;
    data: GetLitActionClientConfigDefault;
    operationId: string;
  } {
    const k6url = new URL(this.cleanBaseUrl + `/get_lit_action_client_config`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "GET",
      k6url.toString(),
      undefined,
      mergedRequestParameters,
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
      operationId: "get_lit_action_client_config",
    };
  }

  getApiPayers(requestParameters?: Params): {
    response: Response;
    data: GetApiPayersDefault;
    operationId: string;
  } {
    const k6url = new URL(this.cleanBaseUrl + `/get_api_payers`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "GET",
      k6url.toString(),
      undefined,
      mergedRequestParameters,
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
      operationId: "get_api_payers",
    };
  }

  getAdminApiPayer(requestParameters?: Params): {
    response: Response;
    data: GetAdminApiPayerDefault;
    operationId: string;
  } {
    const k6url = new URL(this.cleanBaseUrl + `/get_admin_api_payer`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "GET",
      k6url.toString(),
      undefined,
      mergedRequestParameters,
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
      operationId: "get_admin_api_payer",
    };
  }

  /**
   * GET /billing/stripe_config — returns the Stripe publishable key. No auth required; the publishable key is safe to expose.
   */
  billingStripeConfig(requestParameters?: Params): {
    response: Response;
    data: BillingStripeConfigDefault;
    operationId: string;
  } {
    const k6url = new URL(this.cleanBaseUrl + `/billing/stripe_config`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "GET",
      k6url.toString(),
      undefined,
      mergedRequestParameters,
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
      operationId: "billing_stripe_config",
    };
  }

  /**
   * GET /billing/balance — returns the current credit balance for the authenticated user.
   */
  billingBalance(
    headers: BillingBalanceHeaders,
    requestParameters?: Params,
  ): {
    response: Response;
    data: BillingBalanceDefault;
    operationId: string;
  } {
    const k6url = new URL(this.cleanBaseUrl + `/billing/balance`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request("GET", k6url.toString(), undefined, {
      ...mergedRequestParameters,
      headers: {
        ...mergedRequestParameters?.headers,
        // In the schema, headers can be of any type like number but k6 accepts only strings as headers, hence converting all headers to string
        ...Object.fromEntries(
          Object.entries(headers || {}).map(([key, value]) => [
            key,
            String(value),
          ]),
        ),
      },
    });
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
      operationId: "billing_balance",
    };
  }

  /**
   * POST /billing/create_payment_intent — creates a Stripe PaymentIntent and returns the client_secret for use with Stripe.js `confirmCardPayment`.
   */
  billingCreatePaymentIntent(
    createPaymentIntentRequest: CreatePaymentIntentRequest,
    headers: BillingCreatePaymentIntentHeaders,
    requestParameters?: Params,
  ): {
    response: Response;
    data: BillingCreatePaymentIntentDefault;
    operationId: string;
  } {
    const k6url = new URL(this.cleanBaseUrl + `/billing/create_payment_intent`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "POST",
      k6url.toString(),
      JSON.stringify(createPaymentIntentRequest),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          "Content-Type": "application/json",
          // In the schema, headers can be of any type like number but k6 accepts only strings as headers, hence converting all headers to string
          ...Object.fromEntries(
            Object.entries(headers || {}).map(([key, value]) => [
              key,
              String(value),
            ]),
          ),
        },
      },
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
      operationId: "billing_create_payment_intent",
    };
  }

  /**
   * POST /billing/confirm_payment — verifies a succeeded PaymentIntent and credits the account.
   */
  billingConfirmPayment(
    confirmPaymentRequest: ConfirmPaymentRequest,
    headers: BillingConfirmPaymentHeaders,
    requestParameters?: Params,
  ): {
    response: Response;
    data: BillingConfirmPaymentDefault;
    operationId: string;
  } {
    const k6url = new URL(this.cleanBaseUrl + `/billing/confirm_payment`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "POST",
      k6url.toString(),
      JSON.stringify(confirmPaymentRequest),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          "Content-Type": "application/json",
          // In the schema, headers can be of any type like number but k6 accepts only strings as headers, hence converting all headers to string
          ...Object.fromEntries(
            Object.entries(headers || {}).map(([key, value]) => [
              key,
              String(value),
            ]),
          ),
        },
      },
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
      operationId: "billing_confirm_payment",
    };
  }

  getVersion(requestParameters?: Params): {
    response: Response;
    data: GetVersionDefault;
    operationId: string;
  } {
    const k6url = new URL(this.cleanBaseUrl + `/version`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "GET",
      k6url.toString(),
      undefined,
      mergedRequestParameters,
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
      operationId: "get_version",
    };
  }

  /**
   * Merges the provided request parameters with default parameters for the client.
   *
   * @param {Params} requestParameters - The parameters provided specifically for the request
   * @param {Params} commonRequestParameters - Common parameters for all requests
   * @returns {Params} - The merged parameters
   */
  private _mergeRequestParameters(
    requestParameters?: Params,
    commonRequestParameters?: Params,
  ): Params {
    return {
      ...commonRequestParameters, // Default to common parameters
      ...requestParameters, // Override with request-specific parameters
      headers: {
        ...(commonRequestParameters?.headers || {}), // Ensure headers are defined
        ...(requestParameters?.headers || {}),
      },
      cookies: {
        ...(commonRequestParameters?.cookies || {}), // Ensure cookies are defined
        ...(requestParameters?.cookies || {}),
      },
      tags: {
        ...(commonRequestParameters?.tags || {}), // Ensure tags are defined
        ...(requestParameters?.tags || {}),
      },
    };
  }
}
