/**
 * Automatically generated by @grafana/openapi-to-k6: 0.4.1
 * Do not edit manually.
 * lit-api-server
 * Simple API for the Lit Node.
 * Service version: 0.1.0
 */
import { URL, URLSearchParams } from "https://jslib.k6.io/url/1.0.0/index.js";

import http from "k6/http";
import type { Params, Response } from "k6/http";

/**
 * One item from list_api_keys (AccountConfig.sol UsageApiKey).
 */
export interface ApiKeyItem {
  id: string;
  name: string;
  description: string;
  api_key: string;
  expiration: string;
  /** @minimum 0 */
  balance: number;
}

export interface NewAccountResponse {
  api_key: string;
  wallet_address: string;
}

export interface NewAccountRequest {
  account_name: string;
  account_description: string;
  /**
   * Optional initial balance for the account (AccountConfig.accountApiKey.balance). Decimal or hex string; default 0.
   * @nullable
   */
  initial_balance?: string | null;
}

export interface CreateWalletResponse {
  wallet_address: string;
}

export interface LitActionResponse {
  signatures: LitActionSignature[];
  response: string;
  logs: string;
  has_error: boolean;
}

export interface LitActionSignature {
  name: string;
  data: SignWithPkpResponse;
}

export interface SignWithPkpResponse {
  signing_scheme: string;
  signed_digest: string;
  public_key: string;
  signature: string;
}

/**
 * @nullable
 */
export type LitActionRequestJsParams = unknown | null;

/**
 * API key via header.
 */
export interface LitActionRequest {
  code: string;
  /** @nullable */
  js_params?: LitActionRequestJsParams;
}

/**
 * Response for account config operations (add_group, add_pkp_to_group, remove_pkp_from_group, add_usage_api_key, remove_usage_api_key).
 */
export interface AccountOpResponse {
  success: boolean;
}

/**
 * Request for add_group. permitted_actions and pkps are keccak256 hashes as hex strings (with or without 0x). API key via header.
 */
export interface AddGroupRequest {
  /** Name of the group (Group.metadata.name in AccountConfig.sol). */
  group_name: string;
  /** Description of the group (Group.metadata.description in AccountConfig.sol). */
  group_description: string;
  /** Keccak256 hashes of action IPFS CIDs (hex strings). */
  permitted_actions: string[];
  /** Keccak256 hashes of PKP/wallet public keys (hex strings). */
  pkps: string[];
  /** If true, all wallets are permitted to use the group (AccountConfig.sol Group.all_wallets_permitted). */
  all_wallets_permitted?: boolean;
  /** If true, all actions are permitted (AccountConfig.sol Group.all_actions_permitted). */
  all_actions_permitted?: boolean;
}

export interface AddActionToGroupRequest {
  group_id: string;
  /** IPFS CID for the action (will be keccak256-hashed on server). */
  action_ipfs_cid: string;
  /**
   * Optional name for the action (stored in contract metadata).
   * @nullable
   */
  name?: string | null;
  /**
   * Optional description for the action (stored in contract metadata).
   * @nullable
   */
  description?: string | null;
}

export interface AddPkpToGroupRequest {
  /** Group ID (decimal or hex string). */
  group_id: string;
  pkp_public_key: string;
}

export interface RemovePkpFromGroupRequest {
  group_id: string;
  pkp_public_key: string;
}

/**
 * Response for account config operations (add_group, add_pkp_to_group, remove_pkp_from_group, add_usage_api_key, remove_usage_api_key).
 */
export interface AddUsageApiKeyResponse {
  success: boolean;
  usage_api_key: string;
}

/**
 * Request for add_usage_api_key. expiration and balance as decimal strings (e.g. unix timestamp, wei). API key via header.
 */
export interface AddUsageApiKeyRequest {
  expiration: string;
  balance: string;
}

/**
 * API key via header.
 */
export interface RemoveUsageApiKeyRequest {
  usage_api_key: string;
}

/**
 * Request for update_group (AccountConfig.updateGroup). API key via header.
 */
export interface UpdateGroupRequest {
  /** Group ID (decimal or hex string). */
  group_id: string;
  name: string;
  description: string;
  all_wallets_permitted?: boolean;
  all_actions_permitted?: boolean;
}

/**
 * Request for remove_action_from_group. action_ipfs_cid is keccak256-hashed on server. API key via header.
 */
export interface RemoveActionFromGroupRequest {
  group_id: string;
  /** IPFS CID for the action (keccak256-hashed on server). */
  action_ipfs_cid: string;
}

/**
 * Request for update_action_metadata. action_ipfs_cid is keccak256-hashed on server. API key via header.
 */
export interface UpdateActionMetadataRequest {
  group_id: string;
  /** IPFS CID for the action (keccak256-hashed on server). */
  action_ipfs_cid: string;
  name: string;
  description: string;
}

/**
 * Request for update_usage_api_key_metadata (AccountConfig.updateUsageApiKeyMetadata). API key via header.
 */
export interface UpdateUsageApiKeyMetadataRequest {
  usage_api_key: string;
  name: string;
  description: string;
}

/**
 * One item from list_groups, list_wallets, list_wallets_in_group, or list_actions (AccountConfig.sol Metadata).
 */
export interface ListMetadataItem {
  id: string;
  name: string;
  description: string;
}

/**
 * One item from list_groups, list_wallets, list_wallets_in_group, or list_actions (AccountConfig.sol Metadata).
 */
export interface WalletItem {
  id: string;
  name: string;
  description: string;
  wallet_address: string;
  public_key: string;
}

export interface NodeChainConfigResponse {
  chain_name: string;
  /** @minimum 0 */
  chain_id: number;
  is_evm: boolean;
  testnet: boolean;
  token: string;
  rpc_url: string;
  contract_address: string;
}

export type ListApiKeysParams = {
  page_number: string;
  page_size: string;
};

export type ListApiKeysHeaders = {
  /**
   * Account or usage API key. Alternatively use Authorization: Bearer <key>.
   */
  "X-Api-Key": string;
};

export type AccountExistsHeaders = {
  /**
   * Account or usage API key. Alternatively use Authorization: Bearer <key>.
   */
  "X-Api-Key": string;
};

export type CreateWalletHeaders = {
  /**
   * Account or usage API key. Alternatively use Authorization: Bearer <key>.
   */
  "X-Api-Key": string;
};

export type LitActionHeaders = {
  /**
   * Account or usage API key. Alternatively use Authorization: Bearer <key>.
   */
  "X-Api-Key": string;
};

export type AddGroupHeaders = {
  /**
   * Account or usage API key. Alternatively use Authorization: Bearer <key>.
   */
  "X-Api-Key": string;
};

export type AddActionToGroupHeaders = {
  /**
   * Account or usage API key. Alternatively use Authorization: Bearer <key>.
   */
  "X-Api-Key": string;
};

export type AddPkpToGroupHeaders = {
  /**
   * Account or usage API key. Alternatively use Authorization: Bearer <key>.
   */
  "X-Api-Key": string;
};

export type RemovePkpFromGroupHeaders = {
  /**
   * Account or usage API key. Alternatively use Authorization: Bearer <key>.
   */
  "X-Api-Key": string;
};

export type AddUsageApiKeyHeaders = {
  /**
   * Account or usage API key. Alternatively use Authorization: Bearer <key>.
   */
  "X-Api-Key": string;
};

export type RemoveUsageApiKeyHeaders = {
  /**
   * Account or usage API key. Alternatively use Authorization: Bearer <key>.
   */
  "X-Api-Key": string;
};

export type UpdateGroupHeaders = {
  /**
   * Account or usage API key. Alternatively use Authorization: Bearer <key>.
   */
  "X-Api-Key": string;
};

export type RemoveActionFromGroupHeaders = {
  /**
   * Account or usage API key. Alternatively use Authorization: Bearer <key>.
   */
  "X-Api-Key": string;
};

export type UpdateActionMetadataHeaders = {
  /**
   * Account or usage API key. Alternatively use Authorization: Bearer <key>.
   */
  "X-Api-Key": string;
};

export type UpdateUsageApiKeyMetadataHeaders = {
  /**
   * Account or usage API key. Alternatively use Authorization: Bearer <key>.
   */
  "X-Api-Key": string;
};

export type ListGroupsParams = {
  page_number: string;
  page_size: string;
};

export type ListGroupsHeaders = {
  /**
   * Account or usage API key. Alternatively use Authorization: Bearer <key>.
   */
  "X-Api-Key": string;
};

export type ListWalletsParams = {
  page_number: string;
  page_size: string;
};

export type ListWalletsHeaders = {
  /**
   * Account or usage API key. Alternatively use Authorization: Bearer <key>.
   */
  "X-Api-Key": string;
};

export type ListWalletsInGroupParams = {
  group_id: string;
  page_number: string;
  page_size: string;
};

export type ListWalletsInGroupHeaders = {
  /**
   * Account or usage API key. Alternatively use Authorization: Bearer <key>.
   */
  "X-Api-Key": string;
};

export type ListActionsParams = {
  group_id: string;
  page_number: string;
  page_size: string;
};

export type ListActionsHeaders = {
  /**
   * Account or usage API key. Alternatively use Authorization: Bearer <key>.
   */
  "X-Api-Key": string;
};

/**
 * This is the base client to use for interacting with the API.
 */
export class LitApiServerClient {
  private cleanBaseUrl: string;
  private commonRequestParameters: Params;

  constructor(clientOptions: {
    baseUrl: string;
    commonRequestParameters?: Params;
  }) {
    this.cleanBaseUrl = clientOptions.baseUrl.replace(/\/+$/, "");

    this.commonRequestParameters = clientOptions.commonRequestParameters || {};
  }

  listApiKeys(
    params: ListApiKeysParams,
    headers: ListApiKeysHeaders,
    requestParameters?: Params,
  ): {
    response: Response;
    data: ApiKeyItem[];
    operationId: string;
  } {
    const k6url = new URL(
      this.cleanBaseUrl +
        `/list_api_keys` +
        `?${new URLSearchParams(params).toString()}`,
    );
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request("GET", k6url.toString(), undefined, {
      ...mergedRequestParameters,
      headers: {
        ...mergedRequestParameters?.headers,
        // In the schema, headers can be of any type like number but k6 accepts only strings as headers, hence converting all headers to string
        ...Object.fromEntries(
          Object.entries(headers || {}).map(([key, value]) => [
            key,
            String(value),
          ]),
        ),
      },
    });
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
      operationId: "list_api_keys",
    };
  }

  newAccount(
    newAccountRequest: NewAccountRequest,
    requestParameters?: Params,
  ): {
    response: Response;
    data: NewAccountResponse;
    operationId: string;
  } {
    const k6url = new URL(this.cleanBaseUrl + `/new_account`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "POST",
      k6url.toString(),
      JSON.stringify(newAccountRequest),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          "Content-Type": "application/json",
        },
      },
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
      operationId: "new_account",
    };
  }

  accountExists(
    headers: AccountExistsHeaders,
    requestParameters?: Params,
  ): {
    response: Response;
    data: boolean;
    operationId: string;
  } {
    const k6url = new URL(this.cleanBaseUrl + `/account_exists`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request("GET", k6url.toString(), undefined, {
      ...mergedRequestParameters,
      headers: {
        ...mergedRequestParameters?.headers,
        // In the schema, headers can be of any type like number but k6 accepts only strings as headers, hence converting all headers to string
        ...Object.fromEntries(
          Object.entries(headers || {}).map(([key, value]) => [
            key,
            String(value),
          ]),
        ),
      },
    });
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
      operationId: "account_exists",
    };
  }

  createWallet(
    headers: CreateWalletHeaders,
    requestParameters?: Params,
  ): {
    response: Response;
    data: CreateWalletResponse;
    operationId: string;
  } {
    const k6url = new URL(this.cleanBaseUrl + `/create_wallet`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request("GET", k6url.toString(), undefined, {
      ...mergedRequestParameters,
      headers: {
        ...mergedRequestParameters?.headers,
        // In the schema, headers can be of any type like number but k6 accepts only strings as headers, hence converting all headers to string
        ...Object.fromEntries(
          Object.entries(headers || {}).map(([key, value]) => [
            key,
            String(value),
          ]),
        ),
      },
    });
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
      operationId: "create_wallet",
    };
  }

  litAction(
    litActionRequest: LitActionRequest,
    headers: LitActionHeaders,
    requestParameters?: Params,
  ): {
    response: Response;
    data: LitActionResponse;
    operationId: string;
  } {
    const k6url = new URL(this.cleanBaseUrl + `/lit_action`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "POST",
      k6url.toString(),
      JSON.stringify(litActionRequest),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          "Content-Type": "application/json",
          // In the schema, headers can be of any type like number but k6 accepts only strings as headers, hence converting all headers to string
          ...Object.fromEntries(
            Object.entries(headers || {}).map(([key, value]) => [
              key,
              String(value),
            ]),
          ),
        },
      },
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
      operationId: "lit_action",
    };
  }

  getLitActionIpfsId(
    code: string,
    requestParameters?: Params,
  ): {
    response: Response;
    data: string;
    operationId: string;
  } {
    const k6url = new URL(
      this.cleanBaseUrl + `/get_lit_action_ipfs_id/${code}`,
    );
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "GET",
      k6url.toString(),
      undefined,
      mergedRequestParameters,
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
      operationId: "get_lit_action_ipfs_id",
    };
  }

  addGroup(
    addGroupRequest: AddGroupRequest,
    headers: AddGroupHeaders,
    requestParameters?: Params,
  ): {
    response: Response;
    data: AccountOpResponse;
    operationId: string;
  } {
    const k6url = new URL(this.cleanBaseUrl + `/add_group`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "POST",
      k6url.toString(),
      JSON.stringify(addGroupRequest),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          "Content-Type": "application/json",
          // In the schema, headers can be of any type like number but k6 accepts only strings as headers, hence converting all headers to string
          ...Object.fromEntries(
            Object.entries(headers || {}).map(([key, value]) => [
              key,
              String(value),
            ]),
          ),
        },
      },
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
      operationId: "add_group",
    };
  }

  addActionToGroup(
    addActionToGroupRequest: AddActionToGroupRequest,
    headers: AddActionToGroupHeaders,
    requestParameters?: Params,
  ): {
    response: Response;
    data: AccountOpResponse;
    operationId: string;
  } {
    const k6url = new URL(this.cleanBaseUrl + `/add_action_to_group`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "POST",
      k6url.toString(),
      JSON.stringify(addActionToGroupRequest),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          "Content-Type": "application/json",
          // In the schema, headers can be of any type like number but k6 accepts only strings as headers, hence converting all headers to string
          ...Object.fromEntries(
            Object.entries(headers || {}).map(([key, value]) => [
              key,
              String(value),
            ]),
          ),
        },
      },
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
      operationId: "add_action_to_group",
    };
  }

  addPkpToGroup(
    addPkpToGroupRequest: AddPkpToGroupRequest,
    headers: AddPkpToGroupHeaders,
    requestParameters?: Params,
  ): {
    response: Response;
    data: AccountOpResponse;
    operationId: string;
  } {
    const k6url = new URL(this.cleanBaseUrl + `/add_pkp_to_group`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "POST",
      k6url.toString(),
      JSON.stringify(addPkpToGroupRequest),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          "Content-Type": "application/json",
          // In the schema, headers can be of any type like number but k6 accepts only strings as headers, hence converting all headers to string
          ...Object.fromEntries(
            Object.entries(headers || {}).map(([key, value]) => [
              key,
              String(value),
            ]),
          ),
        },
      },
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
      operationId: "add_pkp_to_group",
    };
  }

  removePkpFromGroup(
    removePkpFromGroupRequest: RemovePkpFromGroupRequest,
    headers: RemovePkpFromGroupHeaders,
    requestParameters?: Params,
  ): {
    response: Response;
    data: AccountOpResponse;
    operationId: string;
  } {
    const k6url = new URL(this.cleanBaseUrl + `/remove_pkp_from_group`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "POST",
      k6url.toString(),
      JSON.stringify(removePkpFromGroupRequest),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          "Content-Type": "application/json",
          // In the schema, headers can be of any type like number but k6 accepts only strings as headers, hence converting all headers to string
          ...Object.fromEntries(
            Object.entries(headers || {}).map(([key, value]) => [
              key,
              String(value),
            ]),
          ),
        },
      },
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
      operationId: "remove_pkp_from_group",
    };
  }

  addUsageApiKey(
    addUsageApiKeyRequest: AddUsageApiKeyRequest,
    headers: AddUsageApiKeyHeaders,
    requestParameters?: Params,
  ): {
    response: Response;
    data: AddUsageApiKeyResponse;
    operationId: string;
  } {
    const k6url = new URL(this.cleanBaseUrl + `/add_usage_api_key`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "POST",
      k6url.toString(),
      JSON.stringify(addUsageApiKeyRequest),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          "Content-Type": "application/json",
          // In the schema, headers can be of any type like number but k6 accepts only strings as headers, hence converting all headers to string
          ...Object.fromEntries(
            Object.entries(headers || {}).map(([key, value]) => [
              key,
              String(value),
            ]),
          ),
        },
      },
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
      operationId: "add_usage_api_key",
    };
  }

  removeUsageApiKey(
    removeUsageApiKeyRequest: RemoveUsageApiKeyRequest,
    headers: RemoveUsageApiKeyHeaders,
    requestParameters?: Params,
  ): {
    response: Response;
    data: AccountOpResponse;
    operationId: string;
  } {
    const k6url = new URL(this.cleanBaseUrl + `/remove_usage_api_key`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "POST",
      k6url.toString(),
      JSON.stringify(removeUsageApiKeyRequest),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          "Content-Type": "application/json",
          // In the schema, headers can be of any type like number but k6 accepts only strings as headers, hence converting all headers to string
          ...Object.fromEntries(
            Object.entries(headers || {}).map(([key, value]) => [
              key,
              String(value),
            ]),
          ),
        },
      },
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
      operationId: "remove_usage_api_key",
    };
  }

  updateGroup(
    updateGroupRequest: UpdateGroupRequest,
    headers: UpdateGroupHeaders,
    requestParameters?: Params,
  ): {
    response: Response;
    data: AccountOpResponse;
    operationId: string;
  } {
    const k6url = new URL(this.cleanBaseUrl + `/update_group`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "POST",
      k6url.toString(),
      JSON.stringify(updateGroupRequest),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          "Content-Type": "application/json",
          // In the schema, headers can be of any type like number but k6 accepts only strings as headers, hence converting all headers to string
          ...Object.fromEntries(
            Object.entries(headers || {}).map(([key, value]) => [
              key,
              String(value),
            ]),
          ),
        },
      },
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
      operationId: "update_group",
    };
  }

  removeActionFromGroup(
    removeActionFromGroupRequest: RemoveActionFromGroupRequest,
    headers: RemoveActionFromGroupHeaders,
    requestParameters?: Params,
  ): {
    response: Response;
    data: AccountOpResponse;
    operationId: string;
  } {
    const k6url = new URL(this.cleanBaseUrl + `/remove_action_from_group`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "POST",
      k6url.toString(),
      JSON.stringify(removeActionFromGroupRequest),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          "Content-Type": "application/json",
          // In the schema, headers can be of any type like number but k6 accepts only strings as headers, hence converting all headers to string
          ...Object.fromEntries(
            Object.entries(headers || {}).map(([key, value]) => [
              key,
              String(value),
            ]),
          ),
        },
      },
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
      operationId: "remove_action_from_group",
    };
  }

  updateActionMetadata(
    updateActionMetadataRequest: UpdateActionMetadataRequest,
    headers: UpdateActionMetadataHeaders,
    requestParameters?: Params,
  ): {
    response: Response;
    data: AccountOpResponse;
    operationId: string;
  } {
    const k6url = new URL(this.cleanBaseUrl + `/update_action_metadata`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "POST",
      k6url.toString(),
      JSON.stringify(updateActionMetadataRequest),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          "Content-Type": "application/json",
          // In the schema, headers can be of any type like number but k6 accepts only strings as headers, hence converting all headers to string
          ...Object.fromEntries(
            Object.entries(headers || {}).map(([key, value]) => [
              key,
              String(value),
            ]),
          ),
        },
      },
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
      operationId: "update_action_metadata",
    };
  }

  updateUsageApiKeyMetadata(
    updateUsageApiKeyMetadataRequest: UpdateUsageApiKeyMetadataRequest,
    headers: UpdateUsageApiKeyMetadataHeaders,
    requestParameters?: Params,
  ): {
    response: Response;
    data: AccountOpResponse;
    operationId: string;
  } {
    const k6url = new URL(this.cleanBaseUrl + `/update_usage_api_key_metadata`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "POST",
      k6url.toString(),
      JSON.stringify(updateUsageApiKeyMetadataRequest),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          "Content-Type": "application/json",
          // In the schema, headers can be of any type like number but k6 accepts only strings as headers, hence converting all headers to string
          ...Object.fromEntries(
            Object.entries(headers || {}).map(([key, value]) => [
              key,
              String(value),
            ]),
          ),
        },
      },
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
      operationId: "update_usage_api_key_metadata",
    };
  }

  listGroups(
    params: ListGroupsParams,
    headers: ListGroupsHeaders,
    requestParameters?: Params,
  ): {
    response: Response;
    data: ListMetadataItem[];
    operationId: string;
  } {
    const k6url = new URL(
      this.cleanBaseUrl +
        `/list_groups` +
        `?${new URLSearchParams(params).toString()}`,
    );
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request("GET", k6url.toString(), undefined, {
      ...mergedRequestParameters,
      headers: {
        ...mergedRequestParameters?.headers,
        // In the schema, headers can be of any type like number but k6 accepts only strings as headers, hence converting all headers to string
        ...Object.fromEntries(
          Object.entries(headers || {}).map(([key, value]) => [
            key,
            String(value),
          ]),
        ),
      },
    });
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
      operationId: "list_groups",
    };
  }

  listWallets(
    params: ListWalletsParams,
    headers: ListWalletsHeaders,
    requestParameters?: Params,
  ): {
    response: Response;
    data: WalletItem[];
    operationId: string;
  } {
    const k6url = new URL(
      this.cleanBaseUrl +
        `/list_wallets` +
        `?${new URLSearchParams(params).toString()}`,
    );
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request("GET", k6url.toString(), undefined, {
      ...mergedRequestParameters,
      headers: {
        ...mergedRequestParameters?.headers,
        // In the schema, headers can be of any type like number but k6 accepts only strings as headers, hence converting all headers to string
        ...Object.fromEntries(
          Object.entries(headers || {}).map(([key, value]) => [
            key,
            String(value),
          ]),
        ),
      },
    });
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
      operationId: "list_wallets",
    };
  }

  listWalletsInGroup(
    params: ListWalletsInGroupParams,
    headers: ListWalletsInGroupHeaders,
    requestParameters?: Params,
  ): {
    response: Response;
    data: WalletItem[];
    operationId: string;
  } {
    const k6url = new URL(
      this.cleanBaseUrl +
        `/list_wallets_in_group` +
        `?${new URLSearchParams(params).toString()}`,
    );
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request("GET", k6url.toString(), undefined, {
      ...mergedRequestParameters,
      headers: {
        ...mergedRequestParameters?.headers,
        // In the schema, headers can be of any type like number but k6 accepts only strings as headers, hence converting all headers to string
        ...Object.fromEntries(
          Object.entries(headers || {}).map(([key, value]) => [
            key,
            String(value),
          ]),
        ),
      },
    });
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
      operationId: "list_wallets_in_group",
    };
  }

  listActions(
    params: ListActionsParams,
    headers: ListActionsHeaders,
    requestParameters?: Params,
  ): {
    response: Response;
    data: ListMetadataItem[];
    operationId: string;
  } {
    const k6url = new URL(
      this.cleanBaseUrl +
        `/list_actions` +
        `?${new URLSearchParams(params).toString()}`,
    );
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request("GET", k6url.toString(), undefined, {
      ...mergedRequestParameters,
      headers: {
        ...mergedRequestParameters?.headers,
        // In the schema, headers can be of any type like number but k6 accepts only strings as headers, hence converting all headers to string
        ...Object.fromEntries(
          Object.entries(headers || {}).map(([key, value]) => [
            key,
            String(value),
          ]),
        ),
      },
    });
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
      operationId: "list_actions",
    };
  }

  getNodeChainConfig(requestParameters?: Params): {
    response: Response;
    data: NodeChainConfigResponse;
    operationId: string;
  } {
    const k6url = new URL(this.cleanBaseUrl + `/get_node_chain_config`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "GET",
      k6url.toString(),
      undefined,
      mergedRequestParameters,
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
      operationId: "get_node_chain_config",
    };
  }

  /**
   * Merges the provided request parameters with default parameters for the client.
   *
   * @param {Params} requestParameters - The parameters provided specifically for the request
   * @param {Params} commonRequestParameters - Common parameters for all requests
   * @returns {Params} - The merged parameters
   */
  private _mergeRequestParameters(
    requestParameters?: Params,
    commonRequestParameters?: Params,
  ): Params {
    return {
      ...commonRequestParameters, // Default to common parameters
      ...requestParameters, // Override with request-specific parameters
      headers: {
        ...(commonRequestParameters?.headers || {}), // Ensure headers are defined
        ...(requestParameters?.headers || {}),
      },
      cookies: {
        ...(commonRequestParameters?.cookies || {}), // Ensure cookies are defined
        ...(requestParameters?.cookies || {}),
      },
      tags: {
        ...(commonRequestParameters?.tags || {}), // Ensure tags are defined
        ...(requestParameters?.tags || {}),
      },
    };
  }
}
