//! Request and response shapes for the admin credit portal.

use serde::{Deserialize, Serialize};
use time::OffsetDateTime;

#[derive(Debug, Serialize)]
pub struct CustomerMatch {
    pub stripe_customer_id: String,
    pub email: Option<String>,
    pub wallet_address: Option<String>,
    /// Stripe customer balance in cents. Negative = credits available.
    pub balance_cents: i64,
    /// Human-readable balance, e.g. "$5.00 credit" or "No credits".
    pub balance_display: String,
}

#[derive(Debug, Serialize)]
pub struct LookupResponse {
    pub matches: Vec<CustomerMatch>,
}

#[derive(Debug, Serialize)]
pub struct CustomerPreviewResponse {
    pub found: bool,
    pub email: Option<String>,
    pub wallet_address: Option<String>,
}

#[derive(Debug, Deserialize)]
pub struct GrantRequest {
    /// UUIDv4 generated by the client per submission attempt. Network retries
    /// must reuse the same key; the server dedupes via the grants table's
    /// unique constraint.
    pub idempotency_key: String,
    pub wallet_address: String,
    /// Email snapshot for audit. May be empty if the customer has none.
    #[serde(default)]
    pub email: Option<String>,
    pub cents: i64,
    #[serde(default)]
    pub note: String,
}

#[derive(Debug, Serialize)]
pub struct GrantResponse {
    pub grant_id: i64,
    pub stripe_customer_id: String,
    pub stripe_balance_transaction_id: String,
    pub cents: i64,
    pub new_balance_cents: i64,
    pub new_balance_display: String,
    /// True if the grant was a no-op replay of a previous attempt that had
    /// the same idempotency key.
    pub idempotent_replay: bool,
}

#[derive(Debug, Serialize)]
pub struct GrantRow {
    pub id: i64,
    pub stripe_customer_id: String,
    pub wallet_address: String,
    pub email: Option<String>,
    pub cents: i64,
    pub note: String,
    pub stripe_balance_transaction_id: String,
    #[serde(with = "time::serde::rfc3339")]
    pub created_at: OffsetDateTime,
}

#[derive(Debug, Serialize)]
pub struct GrantsResponse {
    pub grants: Vec<GrantRow>,
}

#[derive(Debug, Serialize)]
pub struct ErrorResponse {
    pub error: String,
}
