use crate::{
    crypto,
    models::{Authority, Manifest},
};
use anyhow::{bail, Result};
use ipfs_hasher::IpfsHasher;
use serde::{Deserialize, Serialize};
use std::{collections::HashMap, sync::LazyLock};
pub const PUBLIC_KEY: &str = include_str!("../actions/public-key.js");
/// Exact template bytes for the authority action and every catalog release id,
/// generated by `npm run build:actions` from `actions/` and pinned in
/// `actions/catalog.lock.json`.
const TEMPLATES: &str = include_str!("../generated/templates.json");
const CATALOG: &str = include_str!("../generated/catalog.json");
#[derive(Clone, Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Release {
    pub id: String,
    pub kind: String,
    pub operation: String,
    pub tier: String,
    pub deprecated: bool,
}
static TEMPLATE_SOURCES: LazyLock<HashMap<String, String>> =
    LazyLock::new(|| serde_json::from_str(TEMPLATES).expect("generated/templates.json"));
static RELEASES: LazyLock<HashMap<String, Release>> = LazyLock::new(|| {
    let catalog: HashMap<String, Release> =
        serde_json::from_str(CATALOG).expect("generated/catalog.json");
    for id in catalog.keys() {
        assert!(
            TEMPLATE_SOURCES.contains_key(id),
            "catalog release {id} has no generated template"
        );
    }
    catalog
});
/// Catalog metadata for a release id, or `None` for an unknown release.
pub fn release(id: &str) -> Option<&'static Release> {
    RELEASES.get(id)
}
pub fn source<T: Serialize>(base: &str, manifest: &T) -> Result<String> {
    Ok(format!("{base}\nconst KEYCHAIN_MANIFEST={};\nasync function main(params){{return KeychainAction.run(KEYCHAIN_MANIFEST,params)}}\n", crypto::canonical(&serde_json::to_value(manifest)?)?))
}
pub fn authority_source(a: &Authority) -> Result<String> {
    source(&TEMPLATE_SOURCES["authority"], a)
}
pub fn secret_source(m: &Manifest) -> Result<String> {
    let Some(base) = TEMPLATE_SOURCES.get(&m.release) else {
        bail!("unknown action release");
    };
    source(base, m)
}
pub fn cid(code: &str) -> String {
    IpfsHasher::default().compute(code.as_bytes())
}
#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn catalog_loads_with_export_and_pinned_templates() {
        let export = release("export").expect("export is required");
        assert_eq!(export.operation, "get");
        assert!(!export.deprecated);
        let stripe = release("stripe_balance").expect("stripe_balance ships");
        assert_eq!(stripe.operation, "stripe.balance");
        assert!(release("not_in_catalog").is_none());
        assert!(TEMPLATE_SOURCES.contains_key("authority"));
        for id in RELEASES.keys() {
            assert!(TEMPLATE_SOURCES.contains_key(id));
        }
    }
    #[test]
    fn unknown_release_has_no_source() {
        let manifest = Manifest {
            v: 2,
            network: "test".into(),
            registry: "https://keychain.test".into(),
            vault_id: "0".repeat(64),
            authority_cid: format!("Qm{}", "a".repeat(44)),
            secret_id: "1".repeat(64),
            release: "not_in_catalog".into(),
        };
        assert!(secret_source(&manifest).is_err());
        assert!(secret_source(&Manifest {
            release: "export".into(),
            ..manifest
        })
        .is_ok());
    }
}
