use crate::{
    crypto,
    models::{Authority, Manifest},
};
use anyhow::{bail, Result};
use ipfs_hasher::IpfsHasher;
use serde::{Deserialize, Serialize};
use std::{collections::HashMap, sync::LazyLock};
pub const PUBLIC_KEY: &str = include_str!("../actions/public-key.js");
/// Current template bytes per name (authority plus every catalog release id),
/// generated by `npm run build:actions` and pinned in `actions/catalog.lock.json`.
const TEMPLATES: &str = include_str!("../generated/templates.json");
/// Every template version ever released, newest first, from `actions/archive/`.
/// Vaults and secrets pin the CID of exact bytes, so the server keeps all of them.
const ARCHIVE: &str = include_str!("../generated/archive.json");
const CATALOG: &str = include_str!("../generated/catalog.json");
#[derive(Clone, Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Release {
    pub id: String,
    pub kind: String,
    pub operation: String,
    pub tier: String,
    pub deprecated: bool,
}
/// One released version of a template: its content hash and full source.
pub struct Version {
    pub hash: String,
    pub code: String,
}
static TEMPLATE_SOURCES: LazyLock<HashMap<String, String>> =
    LazyLock::new(|| serde_json::from_str(TEMPLATES).expect("generated/templates.json"));
static VERSIONS: LazyLock<HashMap<String, Vec<Version>>> = LazyLock::new(|| {
    let raw: HashMap<String, Vec<(String, String)>> =
        serde_json::from_str(ARCHIVE).expect("generated/archive.json");
    let archive: HashMap<String, Vec<Version>> = raw
        .into_iter()
        .map(|(name, versions)| {
            (
                name,
                versions
                    .into_iter()
                    .map(|(hash, code)| Version { hash, code })
                    .collect(),
            )
        })
        .collect();
    for (name, code) in TEMPLATE_SOURCES.iter() {
        assert!(
            archive
                .get(name)
                .is_some_and(|v| v.first().is_some_and(|first| first.code == *code)),
            "current {name} template is not the newest archived version"
        );
    }
    archive
});
static RELEASES: LazyLock<HashMap<String, Release>> = LazyLock::new(|| {
    let catalog: HashMap<String, Release> =
        serde_json::from_str(CATALOG).expect("generated/catalog.json");
    for id in catalog.keys() {
        assert!(
            TEMPLATE_SOURCES.contains_key(id),
            "catalog release {id} has no generated template"
        );
    }
    catalog
});
/// Catalog metadata for a release id, or `None` for an unknown release.
pub fn release(id: &str) -> Option<&'static Release> {
    RELEASES.get(id)
}
/// All released versions of a template, newest first.
pub fn versions(name: &str) -> &'static [Version] {
    VERSIONS.get(name).map(Vec::as_slice).unwrap_or(&[])
}
/// Template names with their version hashes, newest first.
pub fn version_index() -> Vec<(&'static str, Vec<&'static str>)> {
    let mut names: Vec<_> = VERSIONS
        .iter()
        .map(|(name, versions)| {
            (
                name.as_str(),
                versions.iter().map(|v| v.hash.as_str()).collect::<Vec<_>>(),
            )
        })
        .collect();
    names.sort();
    names
}
/// Exact template bytes by content hash, from any template.
pub fn template(hash: &str) -> Option<&'static str> {
    VERSIONS
        .values()
        .flatten()
        .find(|v| v.hash == hash)
        .map(|v| v.code.as_str())
}
pub fn source<T: Serialize>(base: &str, manifest: &T) -> Result<String> {
    Ok(format!("{base}\nconst KEYCHAIN_MANIFEST={};\nasync function main(params){{return KeychainAction.run(KEYCHAIN_MANIFEST,params)}}\n", crypto::canonical(&serde_json::to_value(manifest)?)?))
}
/// Current authority release bound to this vault's authority document.
pub fn authority_source(a: &Authority) -> Result<String> {
    source(&TEMPLATE_SOURCES["authority"], a)
}
/// A specific archived authority release bound to this authority document.
pub fn authority_source_for(a: &Authority, hash: &str) -> Result<String> {
    let Some(version) = versions("authority").iter().find(|v| v.hash == hash) else {
        bail!("unknown authority release");
    };
    source(&version.code, a)
}
/// An authority release as it applies to one vault: template hash and action CID.
pub struct AuthorityVersion {
    pub hash: String,
    pub cid: String,
}
/// Every authority release for this vault, newest first. Any of them is a
/// legitimate signer for the vault; the newest is what new sign-ins should use.
pub fn authority_versions(a: &Authority) -> Result<Vec<AuthorityVersion>> {
    versions("authority")
        .iter()
        .map(|v| {
            Ok(AuthorityVersion {
                hash: v.hash.clone(),
                cid: cid(&source(&v.code, a)?),
            })
        })
        .collect()
}
/// Current release of the secret's catalog action bound to its manifest.
pub fn secret_source(m: &Manifest) -> Result<String> {
    let Some(base) = TEMPLATE_SOURCES.get(&m.release) else {
        bail!("unknown action release");
    };
    source(base, m)
}
/// CIDs of every released version of the secret's action, newest first. Existing
/// secrets pin whichever version they were created under.
pub fn secret_cids(m: &Manifest) -> Result<Vec<String>> {
    let list = versions(&m.release);
    if list.is_empty() {
        bail!("unknown action release");
    }
    list.iter().map(|v| Ok(cid(&source(&v.code, m)?))).collect()
}
pub fn cid(code: &str) -> String {
    IpfsHasher::default().compute(code.as_bytes())
}
#[cfg(test)]
mod tests {
    use super::*;
    fn manifest(release: &str) -> Manifest {
        Manifest {
            v: 2,
            network: "test".into(),
            registry: "https://keychain.test".into(),
            vault_id: "0".repeat(64),
            authority_cid: format!("Qm{}", "a".repeat(44)),
            secret_id: "1".repeat(64),
            release: release.into(),
        }
    }
    #[test]
    fn catalog_loads_with_export_and_pinned_templates() {
        let export = release("export").expect("export is required");
        assert_eq!(export.operation, "get");
        assert!(!export.deprecated);
        let stripe = release("stripe_balance").expect("stripe_balance ships");
        assert_eq!(stripe.operation, "stripe.balance");
        assert!(release("not_in_catalog").is_none());
        assert!(TEMPLATE_SOURCES.contains_key("authority"));
        for id in RELEASES.keys() {
            assert!(TEMPLATE_SOURCES.contains_key(id));
        }
    }
    #[test]
    fn unknown_release_has_no_source() {
        assert!(secret_source(&manifest("not_in_catalog")).is_err());
        assert!(secret_cids(&manifest("not_in_catalog")).is_err());
        assert!(secret_source(&manifest("export")).is_ok());
    }
    #[test]
    fn archive_keeps_every_release_newest_first() {
        // The authority has shipped at least twice; the current bytes come first.
        let list = versions("authority");
        assert!(list.len() >= 2);
        assert_eq!(list[0].code, TEMPLATE_SOURCES["authority"]);
        assert!(template(&list[1].hash).is_some());
        assert!(template(&"0".repeat(64)).is_none());
        let a = Authority {
            v: 2,
            network: "test".into(),
            registry: "https://keychain.test".into(),
            owner: serde_json::from_value(
                serde_json::json!({"kind":"wallet","address":format!("0x{}", "1".repeat(40))}),
            )
            .unwrap(),
        };
        let cids = authority_versions(&a).unwrap();
        assert_eq!(cids.len(), list.len());
        assert_eq!(cids[0].cid, cid(&authority_source(&a).unwrap()));
        assert_eq!(
            cid(&authority_source_for(&a, &list[1].hash).unwrap()),
            cids[1].cid
        );
        assert!(authority_source_for(&a, "nope").is_err());
        let secret = secret_cids(&manifest("export")).unwrap();
        assert_eq!(secret[0], cid(&secret_source(&manifest("export")).unwrap()));
    }
}
