#!/usr/bin/env bash
# Local dev launcher for Lit Chat (README "Local development", Option 1):
# macOS + Docker, no dstack, no Resend. Starts Postgres in Docker, sets env
# (prompting on first run, persisted to .env.local), builds both binaries
# WITHOUT --features production (enables the dev master key + code echo),
# and runs the chat app on :8000 and the admin console on :8100.
#
# Usage:
#   ./scripts/dev-up.sh                # start everything, tail logs (ctrl-c stops apps)
#   ./scripts/dev-up.sh --reconfigure  # re-run the prompts, keep the master key
#   ./scripts/dev-up.sh --down         # stop apps and the Postgres container
#
# Sign-in codes: with no mailer configured, codes are printed to the logs
# (LIT_CHAT_DEV_ECHO_CODES). Watch the tail output for "sign-in code".
#
# NOTE: written for macOS's stock bash 3.2 — keep syntax compatible.

set -euo pipefail

cd "$(dirname "$0")/.."   # repo-relative: lit-chat/

ENV_FILE=".env.local"
DEV_DIR=".dev"
LOG_DIR="$DEV_DIR/logs"
PG_CONTAINER="lit-chat-postgres"
PG_PORT="${LIT_CHAT_DEV_PG_PORT:-5433}"   # 5433 to avoid clashing with a local 5432
CHAT_PORT=8000
ADMIN_PORT=8100

say()  { printf '\033[1;36m[dev-up]\033[0m %s\n' "$*"; }
fail() { printf '\033[1;31m[dev-up]\033[0m %s\n' "$*" >&2; exit 1; }

# ---------------------------------------------------------------------------
# --down: stop everything and exit.

if [ "${1:-}" = "--down" ]; then
  if [ -f "$DEV_DIR/chat.pid" ]; then kill "$(cat "$DEV_DIR/chat.pid")" 2>/dev/null || true; fi
  if [ -f "$DEV_DIR/admin.pid" ]; then kill "$(cat "$DEV_DIR/admin.pid")" 2>/dev/null || true; fi
  rm -f "$DEV_DIR/chat.pid" "$DEV_DIR/admin.pid"
  docker stop "$PG_CONTAINER" >/dev/null 2>&1 || true
  say "stopped apps and the '$PG_CONTAINER' container (data volume kept)."
  exit 0
fi

# ---------------------------------------------------------------------------
# Prerequisites.

command -v docker >/dev/null 2>&1 || fail "Docker is required (Docker Desktop on macOS)."
docker info >/dev/null 2>&1 || fail "Docker daemon is not running — start Docker Desktop first."
command -v cargo >/dev/null 2>&1 || fail "Rust/cargo is required (rustup.rs)."
command -v openssl >/dev/null 2>&1 || fail "openssl is required (ships with macOS)."
if ! rustup toolchain list 2>/dev/null | grep -q '^1\.91'; then
  say "Rust 1.91 toolchain not found; installing via rustup..."
  rustup toolchain install 1.91 || fail "could not install Rust 1.91"
fi

# ---------------------------------------------------------------------------
# First-run configuration -> .env.local (chmod 600, gitignored).
# The master key is generated ONCE and must stay stable: every KEK, session
# MAC, and admin-roster MAC derives from it — regenerating it orphans all
# local history and invalidates the admin roster.

if [ ! -f "$ENV_FILE" ] || [ "${1:-}" = "--reconfigure" ]; then
  say "configuring local environment (${ENV_FILE})"

  if [ -f "$ENV_FILE" ] && grep -q '^LIT_CHAT_DEV_MASTER_KEY=' "$ENV_FILE"; then
    MASTER_KEY=$(grep '^LIT_CHAT_DEV_MASTER_KEY=' "$ENV_FILE" | head -1 | cut -d= -f2-)
    say "keeping existing dev master key (local history stays decryptable)"
  else
    MASTER_KEY=$(openssl rand -base64 32)
    say "generated a new dev master key"
  fi

  printf 'OpenRouter API key for real inference (sk-or-v1-..., empty to skip): '
  read -r -s OR_KEY || OR_KEY=""
  printf '\n'

  printf 'Admin email for the console bootstrap roster (empty to skip): '
  read -r ADMIN_EMAIL || ADMIN_EMAIL=""

  umask 177
  cat > "$ENV_FILE" <<EOF
# Generated by scripts/dev-up.sh — local dev only, never commit.
LIT_CHAT_DEV_MASTER_KEY=$MASTER_KEY
OPENROUTER_API_KEY=$OR_KEY
LIT_CHAT_BOOTSTRAP_ADMINS=$ADMIN_EMAIL
EOF
  umask 022
fi

# shellcheck disable=SC1090
set -a; . "./$ENV_FILE"; set +a

# ---------------------------------------------------------------------------
# Postgres in Docker (idempotent; data survives restarts via named volume).

if docker ps --format '{{.Names}}' | grep -qx "$PG_CONTAINER"; then
  say "postgres already running ($PG_CONTAINER on :$PG_PORT)"
elif docker ps -a --format '{{.Names}}' | grep -qx "$PG_CONTAINER"; then
  say "starting existing postgres container"
  docker start "$PG_CONTAINER" >/dev/null
else
  say "creating postgres container ($PG_CONTAINER on :$PG_PORT)"
  docker run -d --name "$PG_CONTAINER" \
    -e POSTGRES_PASSWORD=postgres \
    -p "$PG_PORT:5432" \
    -v lit-chat-pgdata:/var/lib/postgresql/data \
    postgres:16 >/dev/null
fi

say "waiting for postgres..."
i=0
until docker exec "$PG_CONTAINER" pg_isready -U postgres >/dev/null 2>&1; do
  i=$((i + 1))
  [ "$i" -gt 60 ] && fail "postgres did not become ready in 60s"
  sleep 1
done

# ---------------------------------------------------------------------------
# Build (dev profile, NON-production: enables the dev key source + code echo).

say "building lit-chat + lit-chat-admin (cargo +1.91, dev features)"
cargo +1.91 build --bin lit-chat --bin lit-chat-admin

# ---------------------------------------------------------------------------
# Launch both services.

mkdir -p "$LOG_DIR"

export DATABASE_URL="postgres://postgres:postgres@localhost:$PG_PORT/postgres"
export LIT_CHAT_DEV_ECHO_CODES=true
export RUST_LOG="${RUST_LOG:-info}"

cleanup() {
  say "stopping apps (postgres keeps running; './scripts/dev-up.sh --down' stops it too)"
  [ -n "${CHAT_PID:-}" ] && kill "$CHAT_PID" 2>/dev/null || true
  [ -n "${ADMIN_PID:-}" ] && kill "$ADMIN_PID" 2>/dev/null || true
  [ -n "${TAIL_PID:-}" ] && kill "$TAIL_PID" 2>/dev/null || true
  rm -f "$DEV_DIR/chat.pid" "$DEV_DIR/admin.pid"
}
trap cleanup EXIT INT TERM

say "starting lit-chat on :$CHAT_PORT"
PUBLIC_BASE_URL="http://localhost:$CHAT_PORT" \
ROCKET_PORT="$CHAT_PORT" \
  ./target/debug/lit-chat > "$LOG_DIR/lit-chat.log" 2>&1 &
CHAT_PID=$!
echo "$CHAT_PID" > "$DEV_DIR/chat.pid"

# Consumer runs the migrations; wait for it before the admin binary connects.
say "waiting for lit-chat health..."
i=0
until curl -sf "http://localhost:$CHAT_PORT/health" >/dev/null 2>&1; do
  i=$((i + 1))
  if ! kill -0 "$CHAT_PID" 2>/dev/null; then
    tail -20 "$LOG_DIR/lit-chat.log" >&2
    fail "lit-chat exited during startup (log above; full log: $LOG_DIR/lit-chat.log)"
  fi
  [ "$i" -gt 120 ] && fail "lit-chat not healthy after 120s ($LOG_DIR/lit-chat.log)"
  sleep 1
done

say "starting lit-chat-admin on :$ADMIN_PORT"
PUBLIC_BASE_URL="http://localhost:$ADMIN_PORT" \
ROCKET_PORT="$ADMIN_PORT" \
LIT_CHAT_ADMIN_RP_ID=localhost \
LIT_CHAT_ADMIN_ORIGIN="http://localhost:$ADMIN_PORT" \
  ./target/debug/lit-chat-admin > "$LOG_DIR/lit-chat-admin.log" 2>&1 &
ADMIN_PID=$!
echo "$ADMIN_PID" > "$DEV_DIR/admin.pid"

say "waiting for lit-chat-admin health..."
i=0
until curl -sf "http://localhost:$ADMIN_PORT/health" >/dev/null 2>&1; do
  i=$((i + 1))
  if ! kill -0 "$ADMIN_PID" 2>/dev/null; then
    tail -20 "$LOG_DIR/lit-chat-admin.log" >&2
    fail "lit-chat-admin exited during startup (log above; full log: $LOG_DIR/lit-chat-admin.log)"
  fi
  [ "$i" -gt 60 ] && fail "lit-chat-admin not healthy after 60s ($LOG_DIR/lit-chat-admin.log)"
  sleep 1
done

say ""
say "  chat:  http://localhost:$CHAT_PORT"
say "  admin: http://localhost:$ADMIN_PORT"
if [ -z "${OPENROUTER_API_KEY:-}" ]; then
  say "  (no OpenRouter key configured — streaming returns 'no inference key';"
  say "   rerun with --reconfigure to add one, or import a key in the admin console)"
fi
if [ -n "${LIT_CHAT_BOOTSTRAP_ADMINS:-}" ]; then
  say "  admin login: use '$LIT_CHAT_BOOTSTRAP_ADMINS'; the sign-in code prints below"
fi
say "  attestation endpoints return 503 locally (no dstack socket) — expected."
say ""
say "tailing logs (ctrl-c stops both apps)..."

open "http://localhost:$CHAT_PORT" 2>/dev/null || true

tail -f "$LOG_DIR/lit-chat.log" "$LOG_DIR/lit-chat-admin.log" &
TAIL_PID=$!
# Exit (and clean up) when either app dies, or on ctrl-c.
wait "$CHAT_PID" "$ADMIN_PID"
