use blake3::Hasher;
use std::env;
use std::fs;
use std::io::{BufReader, Read};
use std::path::{Path, PathBuf};
use std::process::Command;
use walkdir::WalkDir;

fn hash_file(path: &Path) -> Option<String> {
    let file = fs::File::open(path).ok()?;
    let mut reader = BufReader::new(file);
    let mut hasher = Hasher::new();
    let mut buffer = [0; 8192];
    while let Ok(bytes_read) = reader.read(&mut buffer) {
        if bytes_read == 0 {
            break;
        }
        hasher.update(&buffer[..bytes_read]);
    }
    Some(hasher.finalize().to_hex().to_string())
}

fn hash_paths(paths: Vec<PathBuf>) -> String {
    let mut hasher = Hasher::new();
    let mut sorted = paths;
    sorted.sort();
    for path in sorted {
        if let Some(h) = hash_file(&path) {
            hasher.update(path.as_os_str().as_encoded_bytes());
            hasher.update(h.as_bytes());
        }
    }
    hasher.finalize().to_hex().to_string()
}

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let src_path = Path::new(&manifest_dir).join("src");
    let version_path = src_path.join("version.rs");

    let mut files: Vec<PathBuf> = WalkDir::new(&src_path)
        .into_iter()
        .filter_map(|e| e.ok())
        .filter(|e| e.file_type().is_file())
        .map(|e| e.path().to_path_buf())
        .filter(|p| p != &version_path)
        .collect();

    files.push(Path::new(&manifest_dir).join("Cargo.toml"));
    files.push(Path::new(&manifest_dir).join("Cargo.lock"));

    let hash = hash_paths(files);

    let (old_hash, old_git_commit) = if version_path.exists() {
        let content = fs::read_to_string(&version_path).unwrap_or_default();
        (
            extract_const_value(&content, "SRC_HASH"),
            extract_const_value(&content, "GIT_COMMIT"),
        )
    } else {
        (String::new(), String::new())
    };

    let git_commit = if hash != old_hash {
        let output = Command::new("git")
            .args(["rev-parse", "HEAD"])
            .current_dir(&manifest_dir)
            .output();
        match output {
            Ok(o) if o.status.success() => String::from_utf8_lossy(&o.stdout).trim().to_string(),
            _ => "unknown".to_string(),
        }
    } else {
        old_git_commit
    };

    let pkg_version = env::var("CARGO_PKG_VERSION").unwrap_or_else(|_| "unknown".to_string());

    let new_content = format!(
        "// This file is auto-generated by build.rs. Do not edit manually.\npub const VERSION: &str = \"{pkg_version}\";\npub const SRC_HASH: &str = \"{hash}\";\npub const GIT_COMMIT: &str = \"{git_commit}\";\n"
    );

    let existing = fs::read_to_string(&version_path).unwrap_or_default();
    if existing != new_content {
        fs::write(&version_path, &new_content).expect("Failed to write src/version.rs");
    }
}

fn extract_const_value(content: &str, name: &str) -> String {
    for line in content.lines() {
        if line.contains(&format!("const {name}:")) {
            if let Some(start) = line.find('"') {
                if let Some(end) = line.rfind('"') {
                    if start < end {
                        return line[start + 1..end].to_string();
                    }
                }
            }
        }
    }
    String::new()
}