// This file is auto-generated by build.rs. Do not edit manually.
pub const VERSION: &str = "0.1.0";
pub const SRC_HASH: &str = "c8081644b87ee2632a7d7fec8bf8f98a6ba2bfe999a51f105d169e107802936c";
pub const GIT_COMMIT: &str = "616796ff55ba6b325f72aaaddb1ce5aba5e4c973";
