// Shared js_params builder: translate the .env venue + stop-policy config
// into the action's params object.
//
// Used by BOTH invocation modes so they run the identical policy identically:
//   - poll.js  passes it as js_params on each local poll
//   - arm.js   freezes it into the lit-triggers trigger's default_params
//
// The TRIGGER_ID generated by setup.js is the idempotency seed: both modes
// derive the same clientOrderId from it, so a double-fire (even across modes)
// resolves to the same venue-side order id.

function buildParams() {
  const {
    VENUE_ID = "binance",
    VENUE_SANDBOX = "true",
    SYMBOL = "BTC/USDT",
    STOP_PRICE,
    AMOUNT,
    FLOOR_PRICE,
    MAX_AMOUNT,
    TRIGGER_ID,
    DRY_RUN = "true",
  } = process.env;

  for (const [k, v] of [
    ["STOP_PRICE", STOP_PRICE],
    ["AMOUNT", AMOUNT],
    ["FLOOR_PRICE", FLOOR_PRICE],
    ["MAX_AMOUNT", MAX_AMOUNT],
    ["TRIGGER_ID", TRIGGER_ID],
  ]) {
    if (!v) {
      throw new Error(
        `${k} missing from .env — set the stop policy first (TRIGGER_ID comes from \`npm run setup\`).`
      );
    }
  }

  return {
    venueId: VENUE_ID,
    sandbox: VENUE_SANDBOX !== "false",
    // CEX credentials (binance/binanceus/coinbase)
    apiKey: process.env.VENUE_API_KEY || undefined,
    secret: process.env.VENUE_SECRET || undefined,
    keyType: process.env.VENUE_KEY_TYPE || undefined,
    // hyperliquid (pkp-eip712) — see README "Hyperliquid option"
    privateKey: process.env.VENUE_PRIVATE_KEY || undefined,
    accountAddress: process.env.VENUE_ACCOUNT_ADDRESS || undefined,
    useActionKey: process.env.VENUE_USE_ACTION_KEY === "true" || undefined,
    proxyUrl: process.env.VENUE_PROXY_URL || undefined,
    // stop policy (decimal strings end to end)
    symbol: SYMBOL,
    stopPrice: STOP_PRICE,
    amount: AMOUNT,
    floorPrice: FLOOR_PRICE,
    maxAmount: MAX_AMOUNT,
    triggerId: TRIGGER_ID,
    dryRun: DRY_RUN === "true",
  };
}

module.exports = { buildParams };
