// Generate the deployable Lit Action by inlining the wasm-bindgen GLUE (~25 KB)
// into the source, so the action carries no `import` specifier.
//
//   node scripts/build-action.js   (or: npm run build:action)
//
// Why: the Lit action bundler only accepts BARE npm import specifiers (it
// resolves them from npm), and we can't publish to npm here — and the Lit API
// gateway caps request bodies well under the 1.5 MB wasm, so we can't inline the
// wasm itself either. The middle path: inline the small glue (no import to
// bundle) and `fetch` the 1.5 MB wasm at runtime from a CDN (a runtime fetch,
// not a bundler import, so a full URL is fine). The action stays ~30 KB.
//
// Produces action/mpcSigner.bundled.js — what setup.js + client/mpcClient.js
// actually send. Re-run whenever you rebuild the wasm (cd wasm && ./build.sh).
// Once `lit-frost-wasm` is published to npm, you can drop this and import it
// directly (bare specifier) like the ECDSA example imports DKLs.

const fs = require("fs");
const path = require("path");

const DIR = path.join(__dirname, "..");
const SRC = path.join(DIR, "action", "mpcSigner.js");
const OUT = path.join(DIR, "action", "mpcSigner.bundled.js");
const GLUE = path.join(DIR, "wasm", "pkg-web", "lit_frost_wasm.js");

function main() {
  if (!fs.existsSync(GLUE)) throw new Error("missing wasm/pkg-web/lit_frost_wasm.js — build it first: (cd wasm && ./build.sh)");

  let glue = fs.readFileSync(GLUE, "utf8");
  // Drop __wbg_init (+ the `export { initSync, __wbg_init as default }` that
  // follows it) — that async default-init is the ONLY user of `import.meta`,
  // which would be a syntax error in a non-module. We init via initSync(bytes).
  const cut = glue.indexOf("async function __wbg_init");
  if (cut === -1) throw new Error("could not find __wbg_init to trim in the glue");
  glue = glue.slice(0, cut).trimEnd();
  // The Lit runtime evals the action body as a SCRIPT (it bundles the `import`
  // separately), so module syntax is illegal. Strip the `export` keywords — the
  // declarations stay in scope as plain script-level bindings.
  glue = glue.replace(/^export\s+/gm, "");
  if (/^\s*export\b/m.test(glue) || /^\s*import\b/m.test(glue)) {
    throw new Error("glue still contains top-level module syntax after stripping");
  }

  let src = fs.readFileSync(SRC, "utf8");
  // Remove the `import init, { ... } from "..."` block — the glue defines those
  // bindings now — and switch the loader from the URL-import `init(...)` to
  // `initSync(bytes)`.
  src = src.replace(/import init, \{[\s\S]*?\} from "[^"]*";[^\n]*\n/, "");
  if (/^\s*import\s/m.test(src)) throw new Error("unexpected leftover import statement in action source");
  src = src.replace(
    "await init(await res.arrayBuffer());",
    "initSync({ module: new Uint8Array(await res.arrayBuffer()) });"
  );

  const banner =
    "// AUTO-GENERATED by scripts/build-action.js — do not edit; edit action/mpcSigner.js.\n" +
    "// wasm-bindgen glue inlined below; the wasm itself is fetched at runtime (WASM_URL).\n";

  const out = banner + glue + "\n\n" + src;
  fs.writeFileSync(OUT, out);
  console.log(`✓ wrote ${path.relative(DIR, OUT)} (${(out.length / 1024).toFixed(0)} KB)`);
}

main();
