// Builds every immutable Lit Action template from the action catalog.
//
// For each actions/<id>/ entry of the pinned library package this validates action.json against the
// catalog definition schema, statically checks action.ts (imports only the
// contributor library; no direct network, eval, dynamic import or runtime access),
// bundles a self-contained IIFE, and pins its SHA-256 in actions/catalog.lock.json.
// A hash that differs from the lock fails the build: deployed action bytes derive
// encryption keys and CIDs, so a change must be an explicit, reviewed release
// (`npm run build:actions -- --update-lock`).
import { build } from "esbuild";
import { mkdir, readFile, readdir, writeFile, stat } from "node:fs/promises";
import { createHash } from "node:crypto";
import path from "node:path";
import { createRequire } from "node:module";
import {
  catalogSchema,
  definitionSchema,
  type ActionDefinition,
  type Catalog,
} from "@lit-protocol/agent-keychain-library/schema";
import { lintActionSource } from "@lit-protocol/agent-keychain-library/lint";

const root = path.resolve(import.meta.dirname, "..");
// The catalog is the pinned @lit-protocol/agent-keychain-library package
// (https://github.com/LIT-Protocol/agent-keychain-library); bump its version in
// package.json to pick up new actions, then --update-lock.
const LIBRARY = "@lit-protocol/agent-keychain-library";
const libraryDir = path.dirname(
  createRequire(import.meta.url).resolve(`${LIBRARY}/package.json`),
);
const catalogDir = path.join(libraryDir, "actions");
const lockPath = path.join(root, "actions/catalog.lock.json");
const updateLock =
  process.argv.includes("--update-lock") ||
  process.env.KEYCHAIN_UPDATE_ACTION_LOCK === "1";
const sha256 = (text: string) =>
  createHash("sha256").update(text).digest("hex");
const fail = (message: string): never => {
  throw new Error(message);
};

async function checkSource(id: string, source: string) {
  const problems = lintActionSource(source);
  if (problems.length) fail(`${id}/action.ts: ${problems.join("; ")}`);
}

const catalog: Catalog = {};
for (const entry of (await readdir(catalogDir, { withFileTypes: true })).sort(
  (a, b) => a.name.localeCompare(b.name),
)) {
  if (!entry.isDirectory()) continue;
  const dir = path.join(catalogDir, entry.name);
  const raw = JSON.parse(await readFile(path.join(dir, "action.json"), "utf8"));
  const parsed = definitionSchema.safeParse(raw);
  if (!parsed.success)
    fail(
      `${entry.name}/action.json is invalid:\n${parsed.error.issues.map((i) => `  ${i.path.join(".")}: ${i.message}`).join("\n")}`,
    );
  const definition: ActionDefinition = parsed.data;
  if (definition.id !== entry.name)
    fail(
      `${entry.name}/action.json declares id ${definition.id}; directory and id must match`,
    );
  const hasCode = await stat(path.join(dir, "action.ts")).then(
    () => true,
    () => false,
  );
  if (definition.kind === "export" && hasCode)
    fail("export/ must not ship action.ts");
  if (definition.kind === "use") {
    if (!hasCode) fail(`${entry.name}/action.ts is missing`);
    await checkSource(
      entry.name,
      await readFile(path.join(dir, "action.ts"), "utf8"),
    );
  }
  catalog[definition.id] = definition;
}
const catalogCheck = catalogSchema.safeParse(catalog);
if (!catalogCheck.success)
  fail(
    `catalog is invalid: ${catalogCheck.error.issues.map((i) => i.message).join("; ")}`,
  );

await mkdir(path.join(root, "generated/entries"), { recursive: true });
const webcryptoPlugin = {
  name: "native-webcrypto",
  setup(b: any) {
    b.onResolve({ filter: /^(node:)?crypto$/ }, () => ({
      path: "crypto",
      namespace: "native-webcrypto",
    }));
    b.onLoad({ filter: /.*/, namespace: "native-webcrypto" }, () => ({
      contents: "export const webcrypto = globalThis.crypto;",
      loader: "js",
    }));
  },
};
async function bundle(entryPoint: string) {
  const { outputFiles } = await build({
    entryPoints: [entryPoint],
    bundle: true,
    write: false,
    format: "iife",
    globalName: "KeychainAction",
    platform: "browser",
    target: "es2022",
    minify: true,
    legalComments: "none",
    charset: "ascii",
    plugins: [webcryptoPlugin],
  });
  const code = outputFiles[0].text;
  if (/import\s*\(/.test(code))
    fail(`${entryPoint}: bundle has a dynamic import`);
  return code;
}
const templates: Record<string, string> = {};
templates.authority = await bundle(path.join(root, "actions/authority.ts"));
for (const definition of Object.values(catalog)) {
  const id = definition.id;
  const entry = path.join(root, `generated/entries/${id}.ts`);
  const useImport =
    definition.kind === "use"
      ? `import use from "${LIBRARY}/actions/${id}/action.ts";\n`
      : "";
  await writeFile(
    entry,
    `// Generated by scripts/build-actions.ts. Do not edit.\n` +
      `import { execute } from "../../actions/secret-common.ts";\n` +
      `import definition from "${LIBRARY}/actions/${id}/action.json";\n` +
      useImport +
      `import type { Manifest } from "../../protocol/schema.ts";\n` +
      `export const run = (manifest: Manifest, params: unknown) =>\n` +
      `  execute(manifest, params, definition as any${definition.kind === "use" ? ", use" : ""});\n`,
  );
  templates[id] = await bundle(entry);
}
const discovery = await readFile(
  path.join(root, "actions/public-key.js"),
  "utf8",
);

// Lock: every template's exact bytes are pinned. Adding an action or cutting a new
// release of an existing one is an explicit `--update-lock`, reviewed in the diff.
const hashes = Object.fromEntries(
  Object.entries(templates).map(([id, code]) => [id, sha256(code)]),
);
hashes.discovery = sha256(discovery);

// Archive: every template version ever released, by content hash, committed under
// actions/archive/<template>/<sha256>.js. Deployed vaults and secrets pin the CID of
// exact bytes, so the server must be able to reproduce any historical version to
// verify receipts and restores, and clients fetch old versions from it by hash.
// Append-only: the build refuses to run if an archived file is missing or altered.
const archiveDir = path.join(root, "actions/archive");
const archive: Record<string, Record<string, string>> = {};
for (const name of (await readdir(archiveDir, { withFileTypes: true }))
  .filter((d) => d.isDirectory())
  .map((d) => d.name)
  .sort()) {
  archive[name] = {};
  for (const file of (await readdir(path.join(archiveDir, name))).sort()) {
    const match = /^([0-9a-f]{64})\.js$/.exec(file);
    if (!match) fail(`actions/archive/${name}/${file}: unexpected file`);
    const code = await readFile(path.join(archiveDir, name, file), "utf8");
    if (sha256(code) !== match[1])
      fail(
        `actions/archive/${name}/${file} does not hash to its name; archived bytes are immutable`,
      );
    archive[name][match[1]] = code;
  }
}
for (const [name, code] of Object.entries(templates)) {
  const hash = hashes[name];
  if (archive[name]?.[hash]) continue;
  if (!updateLock)
    fail(
      `${name} template ${hash.slice(0, 12)}… is not in actions/archive; run --update-lock to release it`,
    );
  await mkdir(path.join(archiveDir, name), { recursive: true });
  await writeFile(path.join(archiveDir, name, `${hash}.js`), code);
  (archive[name] ??= {})[hash] = code;
}
const lock = { v: 1, templates: hashes };
let existing: typeof lock | undefined;
try {
  existing = JSON.parse(await readFile(lockPath, "utf8"));
} catch {}
const drift = Object.entries(hashes).filter(
  ([id, hash]) => existing?.templates?.[id] !== hash,
);
const removed = Object.keys(existing?.templates ?? {}).filter(
  (id) => !(id in hashes),
);
if (removed.length)
  fail(
    `catalog entries were removed: ${removed.join(", ")}. Deployed secrets pin these bytes; mark them deprecated instead.`,
  );
if (drift.length && !updateLock)
  fail(
    `action template bytes differ from actions/catalog.lock.json: ${drift.map(([id]) => id).join(", ")}.\n` +
      `Changing deployed action bytes changes CIDs and encryption keys. If this is an intended new release,\n` +
      `run: npm run build:actions -- --update-lock   and review the lock diff.`,
  );
if (drift.length)
  await writeFile(lockPath, JSON.stringify(lock, null, 2) + "\n");

const generated = (name: string, body: string) =>
  writeFile(path.join(root, "generated", name), body);
await generated(
  "discovery.ts",
  "export default " + JSON.stringify(discovery) + ";\n",
);
await generated(
  "templates.ts",
  "export default " +
    JSON.stringify(templates) +
    " as Record<string, string>;\n",
);
await generated("templates.json", JSON.stringify(templates) + "\n");
// Newest-first per template as [hash, code] pairs: the current release, then
// archived versions (arrays so consumers without ordered maps keep the order).
const ordered = Object.fromEntries(
  Object.entries(archive).map(([name, versions]) => [
    name,
    Object.entries(versions).sort(([a], [b]) =>
      a === hashes[name] ? -1 : b === hashes[name] ? 1 : a.localeCompare(b),
    ),
  ]),
);
await generated("archive.json", JSON.stringify(ordered) + "\n");
// Clients bundle only current templates plus this index of every released hash,
// so they can fetch an older version by hash from the registry and verify it.
await generated(
  "archive-index.ts",
  "export default " +
    JSON.stringify(
      Object.fromEntries(
        Object.entries(ordered).map(([name, versions]) => [
          name,
          versions.map(([hash]) => hash),
        ]),
      ),
    ) +
    " as Record<string, string[]>;\n",
);
await generated(
  "catalog.ts",
  `import type { Catalog } from "${LIBRARY}/schema";\nexport default ${JSON.stringify(catalog, null, 2)} as Catalog;\n`,
);
await generated("catalog.json", JSON.stringify(catalog, null, 2) + "\n");
await generated(
  "release.json",
  JSON.stringify({ protocol: 2, catalog: 1, templates: hashes }, null, 2) +
    "\n",
);
console.log(
  `Built ${Object.keys(catalog).length} catalog actions (${Object.values(
    catalog,
  )
    .map((d) => d.id)
    .join(
      ", ",
    )})${drift.length ? " and updated actions/catalog.lock.json" : ""}`,
);
